@host = http://localhost:4000/api
# @host = https://chat.happycoding.click/chat/api

###
POST  {{host}}/identity/signup
Content-Type: application/json

{
    "Name":"Tri Nguyễn 4",
    "Username":"trint4",
    "Password":"Qwerty@123"
}

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET {{host}}/contacts/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NDk4MTI4ODIsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.dlJGvm7mt2J66pBj1MHpBAO_Ie_C-2tEaT-l5CEj6Qg

###
PUT   {{host}}/contacts
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MbLfIAcfYKJs17LfUHKUMpSsQbSUkx1OBQbactp0KnddRKH9KjyxjyYAcd4GJhZdMGSFslYTD9mZr8gnNl4VBf22cgLcIXIgCdvpM1JhqHHJGnWX2LW4ciNsLlzGPxo_GChY5tMqUyL6MuAu3030Wyp_hqQ2r4_9Z8dYlbFf-W8au2by84wCCONydNvlMA350LmLGAnXGmSKt9U4SEDOJzT0cUUfoWW7mz9aUUR6jvaYa_4wxgqSZmdPfVUibNrgD944i3FUH3Oo_E1bh-pt1R5MyA9fD72KaaNPH3s6Bj1dPcmvoN3X633u0pNHpKm4Xak7kQ3wwi0AfLwGAooxalpWMy-TdhKsNOY4CbYD6XjxMiliY3l37aIr47qnmLUpDJzhyZMrrE6rryFc9kUD2MT4T67kR6ExhLaBM_bNv9UZE9TAxxQDM9tLXVcSnjHJ5oc5lfkWxZ0b6L7KnESr8Zq3Tx8dMqkgglgGmIAtUgWzqCncDn6wXxgzeKOCq3nWbPE37A-vask0ULMlg2TxNac2Wqf80tZP990OGMSx4Uog
Content-Type: application/json

{
    "Name":"Anton Tri 1",
    "Bio":"Hello world!!@@",
    "Avatar":"123"
}

###
POST  {{host}}/identity/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NDk4MTA4OTIsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.k6Zkd5A4hutphqljEij4haLohpO3phMwLgQNGck51eA",
  "userId": "66f270cf9423f7e5257a711e"   
}

###
GET   {{host}}/identity/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NDk4MDM0MTUsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.wCJpFNzfmlu_GwP8p3LpaN7sFt4GNoFY0K0LUfZXjJs