@host = http://localhost:4000/api/v1

### login
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint2",
    "Password":"Qwerty@123"
}

### refresh token
POST {{host}}/identity/refresh
Content-Type: application/json

{
  "refreshToken": "W8hM8AdnXUn0MkkiEJyxFf57+C68mhCmhY23iSfEf5nY/sV+zYIt+tegXTVfGX+IoINXMDoIMqfaOLAuFlGHO5LGEj3ApGX+Xcv+HPudq7O/daNzZyUtTim3vcR2+5/5lRTZWlF0yFFwJYI/kUlNtRAAQCMXn8N8fScbzMzD2oI=",
  "userId": "66f271809423f7e5257a712f"
}


### get conversations
GET  {{host}}/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NDkyMDQyNDcsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.hCWyz2gTNKSzSF3BaCm_LCVi5YpQMIVnyw9kQaZMzY4

### send message
POST  {{host}}/conversations/67c584c5d31e39ba097eea7e/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzE4MDk0MjNmN2U1MjU3YTcxMmYiLCJleHAiOjE3NjIwMTU1MzUsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.k9ooYKFYBd-lWP7D_Rdl5ZknFX7qfrBDaXdJxoVpdKI

{"type":"text","content":"qww"}


### pin message
PUT  {{host}}/conversations/67c584c5d31e39ba097eea7e/messages/6833ea1ba63e39e5e62c66fb/pin?pinned=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NDkyMDQyNDcsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.hCWyz2gTNKSzSF3BaCm_LCVi5YpQMIVnyw9kQaZMzY4

### forward message
POST  {{host}}/conversations/690f7e469419e98d77505dc1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzE4MDk0MjNmN2U1MjU3YTcxMmYiLCJleHAiOjE3NjQ0MzUyMTAsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.9RdafaAVO1vmNIYgxXbiqGXeJTnffzUzPuWXdTOhgo8

{"type":"text","content":"ok fen"}

### reply message
POST  {{host}}/conversations/690f7e469419e98d77505dc1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2NmYyNzBjZjk0MjNmN2U1MjU3YTcxMWUiLCJleHAiOjE3NjQ1MDIzMzQsImlzcyI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayIsImF1ZCI6Imh0dHBzOi8vY2hhdC5oYXBweWNvZGluZy5jbGljayJ9.xyCQnEsc5jNw9NdRtIo8aUNKx24-CQpH9Plquu-c9Ns

{"type":"text","content":"reply message 5","replyId":"692c07d93a5b6b887ae2f75e","replyContent":"reply message 3"}