@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}


###
POST  {{host}}/conversations/66f500cd2052c7a8a265af43/messages
Content-Type: application/json

{"moderator":"66f270cf9423f7e5257a711e","type":"media","content":"","attachments":[{"type":"image","mediaUrl":"https://firebasestorage.googleapis.com/v0/b/myconnect-f2af8.appspot.com/o/img%2Fhanoi7.jpg?alt=media&token=5658e0df-e8fe-4d4e-b2d5-cb099c586e01","mediaName":"test.jpg","mediaSize":208973}]}