@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint2",
    "Password":"Qwerty@123"
}


###
POST  {{host}}/conversations/66ed47b5c0177de7aa8523e2/messages
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PYA4XsKP7-tXD-8yth1KighO730IkJ4ThX2ToWI-_zmp_uuMbxsAzbEfOWxeMaiVwL9sIsuEwJiyvkKY6ZPV97NLifBmxdk4-wvEuXa858WrMgsPz0bBK3X4Viavf8TLWhyp8-Gm2s0-_Q5mT68yetbQ5LHctHxTDkd7h_fma4e66xTykDCorjQUNr5_IQrk3IGKmfe0EXH4DE3y3F-Gq9oAkgtbtWXP_kqb_LewuPPqRTZpN93Dzy4kubXwwASyXSg9tx4vHgEvcaKgsbdwC3oWJj3xzMcMxDs8neHRPWJKuiPTCVOcfW_zvOo8Tgg8JhcEDrpyDeySKIC4HBM8ZTWEVjVd_iy2rMsYuEgo6JOBW0BPWOEKfmEljMGq1qPg12sla1BeZ909PAAkJjDrM_nNdm7vaqQydaaZ6C0xn-ctAXlC_qtkq7N9anbjERjATUXQQbhvS11Jnc8eAESOHtjcXh1tTpEPzWC-O7rUwWM-ErCN672Wxs4cWkbObwkMfJ2NwBR8vIReU6WqB8WtjkW8IT253TdNvVYs6GUBnejg
Content-Type: application/json

{
    "type":"text",
    "content":"hihi 2"    
}