version: "3"

services:
  # mysql-db:
  #   image: mysql:latest
  #   container_name: mysql
  #   volumes:
  #     - db-vol:/var/lib/mysql
  #   #restart: unless-stopped
  #   networks:
  #     - local-network
  #   ports:
  #     - "3300:3306"
  #   environment:
  #     # MYSQL_DATABASE: "CoreDatabase"
  #     # MYSQL_ROOT_PASSWORD: "123456"
  #     TZ: "Asia/Bangkok"
  #     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
  #     #MYSQL_DATABASE: lab-identity-db
  #   secrets:
  #     - MYSQL_ROOT_PASSWORD
  #   restart: always
  #hostname: localhost
  # client:
  #   image: trintdk/client
  #   container_name: client
  #   ports:
  #     - "5002:5000"
  #   restart: always

  # mongo-db:
  #   image: mongo
  #   container_name: mongo
  #   volumes:
  #     - mongo-data-vol:/data/db
  #     - mongo-config-vol:/data/configdb
  #   networks:
  #     - local-network
  #   ports:
  #     - "2700:27017"
  #   restart: always
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: /run/secrets/MONGO_INITDB_ROOT_USERNAME
  #   #   MONGO_INITDB_ROOT_PASSWORD: /run/secrets/MONGO_INITDB_ROOT_PASSWORD
  #   secrets:
  #     - MONGO_INITDB_ROOT_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD

  mongo-db:
    build:
      secrets:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      context: .
secrets:
  # MYSQL_ROOT_PASSWORD:
  #   environment: "MYSQL_ROOT_PASSWORD"
  MONGO_INITDB_ROOT_USERNAME:
    environment: MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD:
    environment: MONGO_INITDB_ROOT_PASSWORD
volumes:
  db-vol:
    external: true
  mongo-data-vol:
    external: true
  mongo-config-vol:
    external: true
networks:
  local-network:
    external: true
