version: "3"

services:
  # setting-api:
  #   image: trintdk/setting-api
  #   container_name: setting-api
  #   depends_on:
  #     - db
  #   ports:
  #     - "4000:5000"
  #   restart: always
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db-vol:/var/lib/mysql
    restart: unless-stopped
    networks:
      - local-network
    restart: always
    environment:
      # MYSQL_DATABASE: "CoreDatabase"
      # MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      #MYSQL_DATABASE: lab-identity-db
    secrets:
      - db_root_password
    ports:
      - "3306:3306"
    #hostname: localhost
  # client:
  #   image: trintdk/client
  #   container_name: client
  #   ports:
  #     - "5002:5000"
  #   restart: always
secrets:
  db_root_password:
    file: db_root_password.txt
    #external: true
volumes:
  db-vol:
    external: true
networks:
  local-network:
    external: true
