version: "3.7"

# services:
#   mongo-db:
#     build:
#       context: .
#       secrets:
#         - MONGO_INITDB_ROOT_USERNAME
#         - MONGO_INITDB_ROOT_PASSWORD
# secrets:
#   MONGO_INITDB_ROOT_USERNAME:
#     environment: MONGO_INITDB_ROOT_USERNAME
#   MONGO_INITDB_ROOT_PASSWORD:
#     environment: MONGO_INITDB_ROOT_PASSWORD

services:
  mongo-db:
    build:
      context: .
      env_file:
        - .env