@host = http://localhost:4000/api

POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}


###
GET  {{host}}/notifications
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7OpUD9QPab6QO5BfhDr8gD2EXyXscbkaOz5XOjh_pRfn7J6L545xAVKNmDJQtOEqHszAcztlhEBeWCRXl2Rc3-WapLK8dAF0yhUmofp4ujazRbXZpbQuwxXuB3292Uh8I6-pRAYQGnF6LbOhH6UiV8i56euzdxWDJJVzMInOhUkgk_cftHPhdS_JpPgfM2Xy67zss3_KXizXMwYEHqfs3OQuHUzFFk65aHHLHl19cB0UmE2GqjKcP4odknWFaXYQ1X9M9g7XUsYlf5PW9deI8sj_vUBF5oUazaa_HT-S5-bYF4DlGYK2N1ev7FO0lGkv-SZUqQ67rg4ssYWmiopDDjricdtVt9DyDT7IsdBxFbEP5daPMr7mOP0mJu9F3s7behzZoG9YhZNwoMRp4A2_LSn6IyBnnjb-pIpi4Bf6XM84gNEq1U5J8zCiYq1OjF3gJ7vHvC5u8mpI29EywpUfjxdrzBejAKgid_6SDUFVRLiuFNrp9g2UlRklW3-SzfW5tdXSS0howADKhuBQvz2_Z7ibmYaRt5rg2L-Jf8qab766g

###
PUT   {{host}}/notifications/66f28410c469ba88ce192519
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7OpUD9QPab6QO5BfhDr8gD2EXyXscbkaOz5XOjh_pRfn7J6L545xAVKNmDJQtOEqHszAcztlhEBeWCRXl2Rc3-WapLK8dAF0yhUmofp4ujazRbXZpbQuwxXuB3292Uh8I6-pRAYQGnF6LbOhH6UiV8i56euzdxWDJJVzMInOhUkgk_cftHPhdS_JpPgfM2Xy67zss3_KXizXMwYEHqfs3OQuHUzFFk65aHHLHl19cB0UmE2GqjKcP4odknWFaXYQ1X9M9g7XUsYlf5PW9deI8sj_vUBF5oUazaa_HT-S5-bYF4DlGYK2N1ev7FO0lGkv-SZUqQ67rg4ssYWmiopDDjricdtVt9DyDT7IsdBxFbEP5daPMr7mOP0mJu9F3s7behzZoG9YhZNwoMRp4A2_LSn6IyBnnjb-pIpi4Bf6XM84gNEq1U5J8zCiYq1OjF3gJ7vHvC5u8mpI29EywpUfjxdrzBejAKgid_6SDUFVRLiuFNrp9g2UlRklW3-SzfW5tdXSS0howADKhuBQvz2_Z7ibmYaRt5rg2L-Jf8qab766g

### Register connection
POST    {{host}}/notifications?token=abcdef
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PKI0lublXSIr0je-e6ifvZucrrDQ7YtDRVJW9X2vHS_zVHSk4GLDYrRt93XIswYryk0UHN6w_eFQq4kBpWDOtfFeX38137Nk3Y_i39oVcOkm0f-zeVMq2Qppd3eElN8vbcRTYLJFGGeyKeaE9_P8FLKLCnbjM2Ly70FaMyYe_rgjY9o8TTFk3_blf1zSClM8i1WyHKB71lrmD88y257tuzzZEgtCAb5GUQVpCVEK_WKX_qoKukLDuYV5u7hD4GzfqgeLDNKLkEMHyy5LoyBwrKE9sRGkLmpG_rgibV_kJcyNOEYbN8Xekrg-41_Q_aGwxlMiLE9_j4JnNmmHSiKAUcFRItwdT7q0SOgqc9nrTBSL2YGEGMOrQKG7Z4jo3coC1EqOAJD3N58OnNn50x5moZI7RVrTHUWyCJaM9dTQ6mfvLFATLeSBRbtXtRBNxpb9QeSB-Ge6Nh0XB3eXBEz4Gpexv4QeKOV3ZzE9JfEuZj7Ewdn0ChyG_YpJSto1dt0CDfmW0vhpQLLVmURU1uDKaNi3skDemmwcptThoPETBlqg
