@host = http://localhost:4000/api

POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}


###
GET  {{host}}/notifications
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPgPokRTUmQ1pP5OOO0ggGQiFaZLangEE2wMA9G2XWpBVHXvcE-by-HOKlroc2gzMiAZkFpPBXfx6K_WWr4OFLyQNIdosbEOkapG_I1ad9KVHN_xsbFbHvu91BMqNHM2uX5JWSwOeEAoJtWXRQ8NjYDosFTeimkTM3kW4C3_ZyfglydP8F3QijlTF6NwaynZZ88bFGnNk-uJcjmEtwv8r7JxpAXZodGvck8WAKqaQjm7GP4XTWrNVf2DvYCZAXG3sv5LdNhvAIxaKy0mGut0-430g3_p8m0ZXAAYs6nhIh7KXdfJRy4z-RQNpgDnyErju-RW4PP7csoVYDjhvGmfl5mqRZPDUfE09lkcBbrkRbpDR9PCdQfRGBxjrMG4cQe6KHL9dJe_ejmQj2h6BiNpa2AfTHatgQ-fnIOVRU0DeYVC58eNqItP7eVWgckoWCUHVikjoseYx9ruB0Qku8e-cOuUDlIS3J6VvCSscg8NQutKJlgfvDYPFH-GdkVuHmm3XsoOMRyg2SxLtcIhv2xCkfRRoDGWIVbtmgjJOZHmRtVKYg


###
PATCH   {{host}}/notifications/66cf2b5e0417d4fdb4b36d67
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPjI5ZlXQOQ1ZKuSvGLLmy40WrsBOmdE_bj1DnAALy1iSVn3ozuqyjQgbJT2RkncEyj5RGeweuWL55Y0xF7Zdg84Dt1OAS8_Bu_uyrIIvCi7ePqDBp-SEvxDjClbbC0MZ9-ZDOZtXFGO3e5i1bIbpWmbD6rkwy08BkMd6TGwHBorvyDENnLvI4jyUWVa1lc3uxWP6J_nPVlaFzZfgnXwprjG4POGNmI_8qO0Z3OKjGlD6OnA52cMzBYJM34I52UMYk7by3nl7cnlNHKy-jSTQd2FBYLZcLXlCAXB8ImPfMAIzUcv9hgp8OaQwTyH9UZsMJrufDPub44ulPnQQ9e48MQwUjXMxuugfbaUTYcqsYvuVs78_wjB4yaRR6UFcYLQ8LzQnnxn_1Fw8gB1Ta3lblZnfXqrEm-dd_6X0vwKGtyFTEX1M6gpunVkDMtUkCXMbEOH8PXYq1zMNbVXKHIeAtaZImrG1r6crSpJG3q3NSV4O8fHFBcgJHturyTm8f-ukAeP6Sjo3k07XPNj_N_SQOjUEmMQGd7aRtKmmzNwvorm8Q

### Register connection
POST    {{host}}/notifications?token=abcdef
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MG5qIBERg39oay1-8I-6uWgwmOfEdm3WPyYfZk1NJpoiSjLrkn21aJih7qxFsupRbcCyE0BqXTUdNsgvRK445vTx44-C6FEitj_FQhpV-3lcjBRhVr33CoSP_UBDEQcC09jKtykEqAf3ZN9wFwdc2XeRDbfg5QstjwFoVyUMAZ662yxAkD3_dgu3tibYacoQ623f6ykCWiaRjaEcMNxoxlWIJVN9k0HH0HJutPkWGJldMU3KGBpq9fcGcIIj2ZZa2jZqTzEsVCgDXOOtiUgQlWu2VZVEaYwxZIFVSzH-2J2J5zIOKpGajscjlbNcEBHak25o4tACLW-JT04z76lW6gF6PhWAMSHr1fhAtSfCazvUaLDSOgnTxu166VhzFRJc8k2Ork-Ka9vhpC8yPqKJw3VTwi-t0BcT8ZT9J-ferVGk_P_Xcly1nnhs7ElLaFZ0NoFIEqwTOlmXarcdzF3GT6YVnwS3ZLMCsIqZrI6ZU1uVz2zpj6quDaOu8mYhF00IH6BjmbSZokj81UiAPZZzc1qJNlvOsdBRAhUFmbE2EGSg
