###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  http://localhost:4000/api/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA

### Send friend request
POST  http://localhost:4000/api/friends/b10aeac9-292f-418d-8da1-e03444db1710
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA


### Accept friend request
PATCH   http://localhost:4000/api/friends/9cab2070-45ff-40ef-86db-d0a622965755
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA
Content-Type: application/json

[{"op":"replace","path":"status","value":"accept"}]

### Cancel friend request
DELETE   http://localhost:4000/api/friends/66a3a2b6-8f67-4d8e-aaed-1696e657c0c9
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA