###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"hayeu",
    "Password":"Qwerty@123"
}


###
GET  http://localhost:4000/api/notifications
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QauwSMG0u9EfN_pO6-tB55LHAeJpIwlWbHMPHrQx91nKOSC9CQDPigbqMn1YgbdJNRPPae8eqg8Lbm-zH2h0tnjqObLfiftDGTyDWKfK1aNK2eBxxEDo9P8QTQSAUf1AYfaKWyjKzxAfaJbPgcoeZrggppukAeyYny4_jbq7vyT8KfVgXc45U3I-RG2V0wseWVMSgI5m3ocfMMmbw29kYQbj5LL5sXuHvtKfKTtDUh01Qcci0keJXrnQr0ch3HlgVnBncuN1JIgVNRRKyP-3UzZhXUK0hQhJxR8s7j9hFARJI4lpWMcPfkr0pQa-tdLpeblXqbjQJYZE0oOFpU9kYhEq4a4rt_CDIfFqMwm7W_HI5Xn6Fwcp3hSv-o829gmcMNd26bQyLS_H4Zo5d-43gtmGu4TBVagMI1QMKOaq4aM1fP1Qbv7XkMnbMVoGzAeszG5S11gZVxWKEYnE47tzn8SWQtiai_LXKzuax_G3A_kM5EPqLkOodG_xwv8nQUKAG-WB2rg8z633jImnSx2JMRDmu-Km8exZU3SZj8HFyHxA


###
PATCH   http://localhost:4000/api/notifications/016ce56e-4764-11ef-95aa-0242ac130003
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q8UfWpCEp-FlxHERV5_U6ocZTeGPVVL4JfcyqusQKnedMCImiJV9NEaMsWRft3GXZR6ar-wavTHo6VsAEi00jOXxN1I__SA5_6Gor7aqQ-YQXFKHzIeof66m2FoPRLc0GJsX4x88WSZFcanLA42Rqrh-wYNrG2gHkFm56UI3Axt4SmfckbUt_krfOIKWO-UuJRrxwGTtfkw1UVzmdwUowu8q0XcSrCdlEk1-7_0fr2rDlwtVGJ-q_hKmfL36vzwWHLl4gSCEGGkGotFmXnt7iBhdPoOcDA0ESUoiGLFAZUavdCU6VzisC-DTMhhlNLlZ51A1PVYUibjq7QuiDAEOBn7WXHCPJ-H62dIcFSC00M9So_B49jHjUdM0sqUCk2idsosIjXyCeioq41wqT3X8Dk4E3-T_KI9z70-TYNqO2eyym9bj6dWvokKjDylU1m0mNtbjtzKUUhSU8M86yBwQ6cAH4hd6AVqqCNtQxe0H0AwcIlIxaeL2QP36RlaAC9y-aDhWsVXKTEJRpiube3LDrzZDC-MHl3f2a2xwDpMRWqZw
Content-Type: application/json

[
	{
        "op": "replace",
        "path": "read",
        "value": false
    }
]

### Register connection
POST    http://localhost:4000/api/notifications?token=1234
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S-_Hsa26v-sRb98Ud2TUAeitAYYMdAfSl-s1kIPKlLBe2bdfeIcYirF6O75vEqXeKEJhnf-x-DnJBcBPkNweZReTuBR3KcizGz9mrEtSOhmTZXsoPRQEFRURNgTZpfeSIjGeyiVmSo3McBLMS89UEEO_rvIV47SdbPKYfuVUrpDxVwqghww8Z-2ASpZFUvxtfeHyR8tltT8ca0K4vPoMJCstdIqSlOl2y2A26EpKcP1BIbbEzMhYw-q0dlLw9XXfvXOucvizUs9sraRykCjez8NIY2nqzM-mQUbSXZHMYg7ZMt16aSjW1ts9sF5aEPX9LkSqOtX4ftHmnllym36UfQJ5U6QDzWl0EeN2QtaaIjn-cj0xcLrF73aij07ssGqdqkLdYdp3x85XnHn4HX8wGJuWMQZBK5aBKJmzL3jG6lRrY-lv9ZEWSRaEoZPx7HLg7Wz5Rpi4XV67f7EYsfU3KFYli-P7EGLFnOmhicm85ZfIr1G0sZZq1oECoXOu7qEFXxUC2Rj5NX6lCI__Z8IqTZI7UdfUil5vuIUs3103jFXA
