@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET {{host}}/contacts/info
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7NcR4NGsR6UXRF-RHWPTKhjK_OgQLwzrjr4061-zFRXIohc4hzWFPsU7y-LRg_DoGCfrRreAWH_daS3GwsrzCM0IldMfGqixjiHPzrfCVdXQfTw2-xTzuM6OMQ6eyzc34gcy8IkC97E40_9R0gY6EPG8GI-Z4JwEqLQB0GMJ75_BHtB-ZFrBAee7ABND_kcpBZkB6VTts2X_XnNjsLVVl_Gjr7Hy85zwle5ckq_X-dPSkxCxmoqUENccxqOGLl-4_Z4D4J88LH08I9m7MID5Fy0p8rWZm8bQnChHJgR3BgyCAOCi71mWDFKnBxrsICNxMHksQVzl4cRB8OGixUxlUnxnrvbf_Uh719DSjYHhPq9yhTsTy6yDIDFApdspVi3OHxS0kFvuu_eeZ3yJuHBycwCjyioqD6RMn03AUQH0l4yO7MuZhT5uzVFu0DjczbxiJNTIkNlHRenJIkUsK-aXvoQXR9FEx8TtE_8Pxxk9kT4ymob5YmyG7TdQctCfpuuRuAp8kUMskve2TFNQVb7qBnj7UTvjajMa-0c8Ota3b-rvg

###
PUT   {{host}}/contacts
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7P1brh6VdKrqx_tr3hjpilSkFmtS3eUOHKUXjG9R2WXoZZPncvs1wXTeDphrDNmlryf_qUBbzUbgwbN_7LFc1SUkfnx3q8oGlynOL31szVTeLnChOJRh8qigfAPA_BlLGN8HBxY9X2hEHF_hfw5HV9D3PM9eyqQCM_0_ex4gLu9wClAobn-s7UTF1o_ClB9ytbNIXihXa2_zgtLuQtOOuApjiJQhNs8o0pANzSM1g7vpMR3oSlQzP9znkkntf2_-CLHQNRkqJIsvmaTKktQL3iaAI84Ohp8BpkhID3JmQbFRW7eCkWYMh9CvXjTDoH5JAMxlIRhLtxlumdcEu8gtur0PqoY3IKZe5XUq867jfDfYuWM5deJjwGBcJ88igl5HB6z5GPhgEC6K1WhBzZObDgtM4vhRS0BZxldHbCA0kmhndUcbwYd9FG8kXNXsdu9VYncWwqzTkvJh5UsSV46aCw3-2O17JgnxiHSGeIuEvAtCPu7KLFuX1E-GrZHCkI24DHQxvR4Z13L5k-66aWQmR7KZ5SQOkvt_FNy86fFS1LoUQ
Content-Type: application/json

{
    "Name":"Anton Tri",
    "Bio":"Hello world!!!..^^!@"
}

###
GET  {{host}}/contacts?name=Trí
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MtRBrOvXR9lf4FE9ONULF3OX8GHMJh7wIcnfr2uCfbmDv-zYz3WXRkeSWVagyzsjXKgFFuY7kwLjJk-_iEqvY4SHXkTR7a_WjO3Zn8s1lGkt8uHW5X6f-qdD5C3yEk8qxXk77wlwOx4DWlKNXQhz7MPEWPJVj2AkVyz81X-wAwHKh4jHTbXZ4lKxH50JviCeYbRODyJWG_Rc-0xzHyEibJvryT2efZyRk4xnDLK0bGJuhDvJF6Uh_LDVKAb73f67EKx9ljqhnnnY0tmidl3BCfJmDx3WN_v5YvHD_aUiJqyQkAzDMUCqB5KOlp9fEq2LIj4wI_BQyKu_RfDZcXsj_oEPJYBZOnLl63bsB0D32wNAVj8_aZudk5VB-2A_n0P8z3seWtdUZlj-JfrB0hL_ARQFYnoArZmGN-R8B03qRvhILQlrqPyEUBKFoP3cshccdi7t6wVkCOdkKoty7f1IVRQHYPh8Mh1sa1JqPOZKl5oL1DdzdzLWIkl8LwMPRpUIojorYig_V9tp3IQg7t9IJNRb7tK6HUKlpKKcblr-0CIA


###
GET  {{host}}/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q6GYlPqVuOQHmbC84D2clTBG-crDAe7n7lx3l9OgOadEwyxEYtbeDyfyfE334aKMT510jH_tQMkqWUlvA9Q0uXso92YBE9k4jT0HpLlMwmMZNgA34Xk5WqXG3doFXk7vbmo8oaVW9Dp8m6zjXoqAzrWwnv1SI2khp7THIDW8LUA3l--x_3a2RUZjM_Fw2AMhs6eVaEHxKR-63c6JhMzH_1CSSFdzlg2Ja9JPOObHGi3mkuN8Qz1kVilQdYAZr3ycuHThrbSsMgt5uYTFaASPKz9sGuH82ZvvjPj-2X70Ay5n13Ts8gfsNvRh3g-9ROehMdslDSf1hbqJ-mPeetkVNLtDfOAotLA5IeJ7NeGw31_RbRy5CEfjnJKRXVvIWU2zKgWxKeStotjgaGygLsCH1Rt0982QCtHJ6OsF-UCyD1aWcE21TlxgTxWr0ES867nw-nr_H4Mvv_WVtrSUqRwSr4mwCZPnYHRqx5XEku5Q4wU32BteQPQ8jn5vuFN0zB34ygGmkqfXsFq855jUYgMB-b2gkoFU1AK4kQmBjBWu2KRg