@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint4",
    "Password":"Qwerty@123"
}

###
GET {{host}}/contacts/info
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Nx1nfBHNByYPv8rx9o6_oX2lDzh-OxgVyMsGtf-JcMz3HQLkA8eoEMRy22W54Bq2a9hk5Tn6CZDFukuwZ2Zvfw_V30RILUyckBIJO4XbmiYp4OrRBDuNzsyLOBN03tOYc9etlKxy3drXwV7kq0xG7LDKl1oXus69jqLMgOtnE5WLiFrnfAmf1vYjYK7SD473sjxmpcPBn7BdI7v3Sci1K3GorCjQGkxZUiQM95J-sWLr8Qnf5GPfSh0DImfyaqJ8YMefiWLFpJk1Brrp-k5J_R-au06QbkLU6fLFpl7qn5tVP7G33tRkedqbvDXzE45uJcxh_xqGpwBIvH9XiNRwJDb_WGB6wbBHbyH5TSRN9reEMVl5HHY7C8CeS4_abne2vbl5cQATyLWckkhdPXTfrA0BVdUsGE6IbfpbpwsWpetfuTuPA4C7UylWW75Za8-beCeB73QplDshiwvBQrqTkCE0IDpZIoSo7qRsXjHLkzM4M8R8IXe4MayM3oZSU1UQGRefO1ex-b_sA2WivlEQHHw6Hai35_E3t9k-CEyo95iw

###
PUT   {{host}}/contacts
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MtRBrOvXR9lf4FE9ONULF3OX8GHMJh7wIcnfr2uCfbmDv-zYz3WXRkeSWVagyzsjXKgFFuY7kwLjJk-_iEqvY4SHXkTR7a_WjO3Zn8s1lGkt8uHW5X6f-qdD5C3yEk8qxXk77wlwOx4DWlKNXQhz7MPEWPJVj2AkVyz81X-wAwHKh4jHTbXZ4lKxH50JviCeYbRODyJWG_Rc-0xzHyEibJvryT2efZyRk4xnDLK0bGJuhDvJF6Uh_LDVKAb73f67EKx9ljqhnnnY0tmidl3BCfJmDx3WN_v5YvHD_aUiJqyQkAzDMUCqB5KOlp9fEq2LIj4wI_BQyKu_RfDZcXsj_oEPJYBZOnLl63bsB0D32wNAVj8_aZudk5VB-2A_n0P8z3seWtdUZlj-JfrB0hL_ARQFYnoArZmGN-R8B03qRvhILQlrqPyEUBKFoP3cshccdi7t6wVkCOdkKoty7f1IVRQHYPh8Mh1sa1JqPOZKl5oL1DdzdzLWIkl8LwMPRpUIojorYig_V9tp3IQg7t9IJNRb7tK6HUKlpKKcblr-0CIA
Content-Type: application/json

{
    "Name":"Anton Tri",
    "Bio":"Hello world!!!.."
}

###
GET  {{host}}/contacts?name=Trí
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MtRBrOvXR9lf4FE9ONULF3OX8GHMJh7wIcnfr2uCfbmDv-zYz3WXRkeSWVagyzsjXKgFFuY7kwLjJk-_iEqvY4SHXkTR7a_WjO3Zn8s1lGkt8uHW5X6f-qdD5C3yEk8qxXk77wlwOx4DWlKNXQhz7MPEWPJVj2AkVyz81X-wAwHKh4jHTbXZ4lKxH50JviCeYbRODyJWG_Rc-0xzHyEibJvryT2efZyRk4xnDLK0bGJuhDvJF6Uh_LDVKAb73f67EKx9ljqhnnnY0tmidl3BCfJmDx3WN_v5YvHD_aUiJqyQkAzDMUCqB5KOlp9fEq2LIj4wI_BQyKu_RfDZcXsj_oEPJYBZOnLl63bsB0D32wNAVj8_aZudk5VB-2A_n0P8z3seWtdUZlj-JfrB0hL_ARQFYnoArZmGN-R8B03qRvhILQlrqPyEUBKFoP3cshccdi7t6wVkCOdkKoty7f1IVRQHYPh8Mh1sa1JqPOZKl5oL1DdzdzLWIkl8LwMPRpUIojorYig_V9tp3IQg7t9IJNRb7tK6HUKlpKKcblr-0CIA


###
GET  {{host}}/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q6GYlPqVuOQHmbC84D2clTBG-crDAe7n7lx3l9OgOadEwyxEYtbeDyfyfE334aKMT510jH_tQMkqWUlvA9Q0uXso92YBE9k4jT0HpLlMwmMZNgA34Xk5WqXG3doFXk7vbmo8oaVW9Dp8m6zjXoqAzrWwnv1SI2khp7THIDW8LUA3l--x_3a2RUZjM_Fw2AMhs6eVaEHxKR-63c6JhMzH_1CSSFdzlg2Ja9JPOObHGi3mkuN8Qz1kVilQdYAZr3ycuHThrbSsMgt5uYTFaASPKz9sGuH82ZvvjPj-2X70Ay5n13Ts8gfsNvRh3g-9ROehMdslDSf1hbqJ-mPeetkVNLtDfOAotLA5IeJ7NeGw31_RbRy5CEfjnJKRXVvIWU2zKgWxKeStotjgaGygLsCH1Rt0982QCtHJ6OsF-UCyD1aWcE21TlxgTxWr0ES867nw-nr_H4Mvv_WVtrSUqRwSr4mwCZPnYHRqx5XEku5Q4wU32BteQPQ8jn5vuFN0zB34ygGmkqfXsFq855jUYgMB-b2gkoFU1AK4kQmBjBWu2KRg