@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET {{host}}/contacts/info
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPglBOdoE4Tak7enigva0Er2UY08GiT3JIuz0leMCDIC9JkHB89gsGnNMECNecXxY7XfeMJJJkElArLyDptSCIWgFHGPIQ4wQ-_nn1E1A0RQKqrHoaKkUif47Q5WerBJ9UAsaVEluhR8avO8qoZxO0tINdiOUME1shlV4uJ7L_XXvw_HiP--igKM4MHJoVA0qol4uADsV-ul-BK_MyMvichqOmEe3ei13UThYfPN-H_gL8_PV7fMNTbskWBcNEqLWcVArpVGNkNyOGE2wMH5rjgyXa_ImwAIw1unMr8pJSTD5VXpOPSFP4eqNcX3DNUjYIf7oV8avnLucP4-vOxJBqPU455m5k9msOT21ah-d2q3qknWcMBjMY78jGYvmIvTysF3xp5Bj-W1om4EoyQxlduiVugRW6chQA7kgvyMgpOxnhzLPifPz6KN9frifHsB-zOzs25iySywrEAlStDGUP5hZZtqGR5_ncSHJt9NWt5CKeCdaMsKdBrs_ovcqUV6_7EIlyXCRkjvJPIB9hBqJ-ObnWF2EthKQ7reLiDs5IUOZg

###
PUT   {{host}}/contacts
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPglBOdoE4Tak7enigva0Er2UY08GiT3JIuz0leMCDIC9JkHB89gsGnNMECNecXxY7XfeMJJJkElArLyDptSCIWgFHGPIQ4wQ-_nn1E1A0RQKqrHoaKkUif47Q5WerBJ9UAsaVEluhR8avO8qoZxO0tINdiOUME1shlV4uJ7L_XXvw_HiP--igKM4MHJoVA0qol4uADsV-ul-BK_MyMvichqOmEe3ei13UThYfPN-H_gL8_PV7fMNTbskWBcNEqLWcVArpVGNkNyOGE2wMH5rjgyXa_ImwAIw1unMr8pJSTD5VXpOPSFP4eqNcX3DNUjYIf7oV8avnLucP4-vOxJBqPU455m5k9msOT21ah-d2q3qknWcMBjMY78jGYvmIvTysF3xp5Bj-W1om4EoyQxlduiVugRW6chQA7kgvyMgpOxnhzLPifPz6KN9frifHsB-zOzs25iySywrEAlStDGUP5hZZtqGR5_ncSHJt9NWt5CKeCdaMsKdBrs_ovcqUV6_7EIlyXCRkjvJPIB9hBqJ-ObnWF2EthKQ7reLiDs5IUOZg
Content-Type: application/json

{
    "Name":"Anton Tri",
    "Bio":"Hello world!!!..^^!@@@@@@@"
}

###
GET  {{host}}/contacts?name=Nguyen
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPh5yKX0j7c62C4i4h0DuVA_RWoPQbV5ykWBAbeEo9_Vvlo2ht92CCq-62i6FQHztT54SPMFotdfhCU9Cf5gxJQGj3N184m8bRGv9Oi6j8zGWIT9XvEWCReUNiGeoWwjCOm2P7SulxJjHHqrmYEz5fnk0f2cPIY36vCbewGD2EryOmTzRNvBnYJj7g_zMlLXrEAKLu3bNU8AnX6iuTY_nN9vTyT0is_uHJZ5aLzDbt5QJUb0qiwlHdCHavJJ2qsiJE6UolLeNr9oJfL4klimNRvrra5918MMnSkV6DncdVcUpLl-sQYDz0P_8IMsoNzELgXGsaeJZtdlFj8aecjCRYfOvVWu19f1xjiP75fFm4sz9OXcx5OfqHQErvD9VDYZumyQiViZfmMrqNbyDrLFvqXQJX_JOuMjXf9wDCTLJrnFgRfTb3WD1_h2QYDBBH6XF2MutAp3vjobIf-2poeuAdNbpXSjzpaWiBEn8lNeIj7la_D03V3lKfeqJjdRAjB1hLlfHoU_iQBO9Dvtw2wUDWMYvOtcTco47gztpKtv0NtGng


###
GET  {{host}}/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q6GYlPqVuOQHmbC84D2clTBG-crDAe7n7lx3l9OgOadEwyxEYtbeDyfyfE334aKMT510jH_tQMkqWUlvA9Q0uXso92YBE9k4jT0HpLlMwmMZNgA34Xk5WqXG3doFXk7vbmo8oaVW9Dp8m6zjXoqAzrWwnv1SI2khp7THIDW8LUA3l--x_3a2RUZjM_Fw2AMhs6eVaEHxKR-63c6JhMzH_1CSSFdzlg2Ja9JPOObHGi3mkuN8Qz1kVilQdYAZr3ycuHThrbSsMgt5uYTFaASPKz9sGuH82ZvvjPj-2X70Ay5n13Ts8gfsNvRh3g-9ROehMdslDSf1hbqJ-mPeetkVNLtDfOAotLA5IeJ7NeGw31_RbRy5CEfjnJKRXVvIWU2zKgWxKeStotjgaGygLsCH1Rt0982QCtHJ6OsF-UCyD1aWcE21TlxgTxWr0ES867nw-nr_H4Mvv_WVtrSUqRwSr4mwCZPnYHRqx5XEku5Q4wU32BteQPQ8jn5vuFN0zB34ygGmkqfXsFq855jUYgMB-b2gkoFU1AK4kQmBjBWu2KRg