@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}
 
###
GET  {{host}}/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PkbqkxnlZq2Sdoqf_RFFH16Xhc1yMSfYwlmQ0g-7Yy-smHLSG4g84PSksh3vOUKGxdYtrdVvCgAZzhVuhOPB9ZZFaJJXuc7Tvm32Y3WdlRsWTWNbONqhvKsb6KrYKNpn3i4g8XLLGCWT96EviIbna0prPF5DeNNupciqjGfAHqiDxjxklL9q9Y2UccxhxtR4C6BsdbofFycvx2sdcp7HTG-lFqG4EruzQCgQ-zG0czB3S1TbVQAz8RgTj_yvSmiDldZOKtBR2JyZWEttYaNmny8SLzxWPFoP-0IngTYZwTYubT-WWsMK83_Eb7i3_3pYf0r7anbX4WMAsbKGyvum9UiIo6rHgjuUce7bCDPE1uyQm7Vnjf7npxsalOq_2At7sLC71MJRINjSuAepkGcEjZySSHbLRfW0FLk1QwFFYzZFKx-oFwAc-184xPXI8115o47rnvWkVjoMLUIvYiRG-A5itgeW6F9wGhrUHRiK3B6_DQOePQmVkuxCwrfq8DZYCzk-_4m5vG-3UVLAqfRxxnhfA1BEY7THQN8j13UX0uqA
 
###
GET  {{host}}/friends/66ea74078056549b836d69e6
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PkbqkxnlZq2Sdoqf_RFFH16Xhc1yMSfYwlmQ0g-7Yy-smHLSG4g84PSksh3vOUKGxdYtrdVvCgAZzhVuhOPB9ZZFaJJXuc7Tvm32Y3WdlRsWTWNbONqhvKsb6KrYKNpn3i4g8XLLGCWT96EviIbna0prPF5DeNNupciqjGfAHqiDxjxklL9q9Y2UccxhxtR4C6BsdbofFycvx2sdcp7HTG-lFqG4EruzQCgQ-zG0czB3S1TbVQAz8RgTj_yvSmiDldZOKtBR2JyZWEttYaNmny8SLzxWPFoP-0IngTYZwTYubT-WWsMK83_Eb7i3_3pYf0r7anbX4WMAsbKGyvum9UiIo6rHgjuUce7bCDPE1uyQm7Vnjf7npxsalOq_2At7sLC71MJRINjSuAepkGcEjZySSHbLRfW0FLk1QwFFYzZFKx-oFwAc-184xPXI8115o47rnvWkVjoMLUIvYiRG-A5itgeW6F9wGhrUHRiK3B6_DQOePQmVkuxCwrfq8DZYCzk-_4m5vG-3UVLAqfRxxnhfA1BEY7THQN8j13UX0uqA

### Send friend request
POST  {{host}}/contacts/66ea3446603cc47da304fb6f/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7N9QnsmDRMaOpasYMTPLyjUgaTSm9sLqXpVq0KIJ89ksS_DV2GhRbrP3Azdaxtczvryy6VAQPPNzQYDZKkhA2m_vKxShTZbOfNAAMNQS2h2j9XlKW3qCzO55-C1_qgsQo3pXmD5MBppJN-Ky5Lk0EV34Y0sNf7BAFpxKxghAT7WMwlNPyP4pK3p4a_lZivWmIvCZSAfrWzqyCQzMT8QApQFcjhVzS1B4q1gHuB1zGS_OMJYOrfMB-xVAOMIYFdTc0PU4VsJaEZW_YwwJBdYdvMh7YLvlDjCh3h4Fwo4Yjo4SUlEwCk08fLIJmM6-zEl_iI7R87Mpjr8OLlW0CESZT14LUIZ6XsLxR6tfcw4toJ9eK2HHTL8aFyJrX5bzwxkTT_NsmASWa5TyPAiWyuI-K8qUg9UhLK6M2fzhWcAoLzUFkcU6Heb-2dUW9kFMAJkS59-uHmo9mOz0VmVrn-jcJ_7nsVlF-xqNletICpkNJdpPR9gcjd8Yl_EYPdhWgwcyB5qMfZOjzpOZL-IReKxqTx4Y3Q2KkvEtRNCx_h37HwOzA

### Accept friend request
PUT   {{host}}/friends/66ea36330433a8aa0d57b327
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7O4FSy5G-7wtLmhM2Q77HjK2sSvyHhp20tJH97QLJqWQRdPNE4m_nEDx7rxT2NDLFTDVpmkbA-mVj_R3C6KnwxA7x_G9snZAE-0vD63pve9pRkmpqM47ofKA2zFLlhsu1YTtaZENtH2pYRlXe5OhN47PlI66O4DD2-igq5ByF6itIDkdrftDPyu_Hs4UWMzEHNgv32sJLqUYYOk6UP3yA3mWq5LfMN3p_Ip5NzcUmnlXOAiC3PLkhYi6j7BJD6ft-oYmvVs-XAbp518I-8xITwmV5sLGkZqZVcrolwQBTAOIPeggaPb_1ElEDzmLUcGVN5ZW8Su3tB-JP3SneG-4vLGrtYqPYUc82_HxeH4Hyo-U4c4D7rLqag6VoFAI6U0G6LGAwCgnTFbUyJ3ACrawEmapgEBazRKYP9kqAH5PttgT8ohtO64v_R9xvgDIO19-Nj2oRiiLovgvdraVhKy_xC58eh2Gaylpz74OkVjscQoDYJIWv_wJfiadDDzrk57GBkZ5cbS8GA6V_l3eN7HDdVOXQU-IkFNWJ27rpuIqvUSBw
Content-Type: application/json

### Cancel friend request
DELETE   {{host}}/friends/66ea9f67e10326bddefadd76
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7MabI3dPGF3v0ixPIu1ff-KtsZF36mKv2yWlIeJcTL-xJSGGv9q_7ZTd4XTL_idbJCc6pozU03r4gwvdPIKHD5ecI_VlBpNdunR_mAtU7J3RGEa8Oi6MDXskTbA2U3iRDMLmhIMoMngR1fwC5SFkr1Up80Y_3T8hBkfrYHv85Y5BcP8GeDKD2t1mK1gnvpVbIwEopi5PKqtfQjanjhItRCWfzB3E9K8AQpng_X3UApoS9SVZ-AFP3yPeUeGcHdXSonRduLi1FMmkH5ys1nlMG8GTjU9FOjpX6jqKipswEBbn2jwVD3RUua4IGwPIsA9Pz1Skb-t5oy_qkNnMxTU_9f9qWTD1I9hByr9vHIf7mEyhy3eUK9OlMs7WyxwwOPa4UWWsKdxdkc7O8fMQnHb1PtxnzHn1rPVQCEAUmIeA4K2bODcEyl3GuMCyV8R6OmHRU2fadVzQMP0p89MW-gy9iP3uqtAQWiuEnqWrEF3gZPkZWeJPdBGJTKQk6l69MOOSitqYYhZ99TZuxC9dIBpsOtferMSUp5Io_byyDij-Otuig