@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}
 
###
GET  {{host}}/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Nfr8n6R5IYRIWEOrt_x6sEcOV6khIllPzv6AxWdBrJZQfkhWMZn9-OfzDIiG0ylNIHCA2hUBNfK6pp-XbmvkBUIPZkvFc44uSiP8BzdHNI4e4th4GRgnMDUSTTPxPq-Zg_BfOO0Fg2HN0tDcmymSXPuh4MkJiie9ATf___K2GV-M7WmZjenQTCr9LB1-48SXX5lR9Sbp79or5yOQ27gJ78WK9C4PfWToKLrhXOYmjz3za3OSn9FkW4kcPz2d1XePojTjGFhxR7JAcTHN4zc0U2HxP41L8Z2psvKeZiuvR0z_f7-u-Kz3tMoYHIxcB4jpPx3n4vQfweGl-iX7qV6IUS3w6ViDI6BfIJYkVvrZXrb-Q2uMiJaCRtUPZ_CkkB_AMyvVxfeazi4EKcIrkAGQr-Kskkr3Gp2smQ93jmUAQoVGs2LVrhHo367tQooJsAX36g-VvIdFCB0cgku3tEYj4lZpP7jUzAFdsHgzehBCJUNeNtPwxg6qhsu44SUdljTzdQSA0Wr-myKBcM4s-IweOkSwDr8jp49quPfbaSvFtg4w
 
###
GET  {{host}}/friends/66f2857bc469ba88ce192577
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Nfr8n6R5IYRIWEOrt_x6sEcOV6khIllPzv6AxWdBrJZQfkhWMZn9-OfzDIiG0ylNIHCA2hUBNfK6pp-XbmvkBUIPZkvFc44uSiP8BzdHNI4e4th4GRgnMDUSTTPxPq-Zg_BfOO0Fg2HN0tDcmymSXPuh4MkJiie9ATf___K2GV-M7WmZjenQTCr9LB1-48SXX5lR9Sbp79or5yOQ27gJ78WK9C4PfWToKLrhXOYmjz3za3OSn9FkW4kcPz2d1XePojTjGFhxR7JAcTHN4zc0U2HxP41L8Z2psvKeZiuvR0z_f7-u-Kz3tMoYHIxcB4jpPx3n4vQfweGl-iX7qV6IUS3w6ViDI6BfIJYkVvrZXrb-Q2uMiJaCRtUPZ_CkkB_AMyvVxfeazi4EKcIrkAGQr-Kskkr3Gp2smQ93jmUAQoVGs2LVrhHo367tQooJsAX36g-VvIdFCB0cgku3tEYj4lZpP7jUzAFdsHgzehBCJUNeNtPwxg6qhsu44SUdljTzdQSA0Wr-myKBcM4s-IweOkSwDr8jp49quPfbaSvFtg4w

### Send friend request
POST  {{host}}/contacts/66f271809423f7e5257a712f/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7NUDcOTMAL_r0r1aowfOQmfIjiKXJsjhgJEyPJ_Wwgcr-pWI1JlkvZ7eVrIzBkrF-2iI2jTIkSiY5Zw5Dzx9SBVg9GE9C43OOhlEjCdhNnMA3_jaRcKZxq4jciwwg2z0dW9R6PPulpF4F467sJX2K2KN5hDD2w07viawlZxdMtHiZVlX4bx4USqVg4cPpKRMotgrHFmxpUo6cxennIv9qWzj072kAZO8p0ejqxl0NyOryRPjKs3oT1PDCPPNTmH_BF7i2iqtit22zMPz9VziIQv7bw8VeQM3QDmFTfSABB8xvp5rEtZkphX_mTnpM41S-m0KDROF-7ktIePi66nE8d-3RjP5oHrl4eul8A4dsr9uBOw_J9ZvoJJlRg53wpDpbTBiymI6LZybxdxE9LF-n1-yexpieCs5DwROb7hUqCv9AncskyecjupHqwKmU3a6M6E3f0JNZTf86SF9OgzA0S7PonDPtjwR7_owjEHnaMnQ2XFiN20dEAUNhLZFMJwoI8a4uuLxilus6i61gv6rxrfgCwXSg0SQJEQKJ0SoG-7kg

### Accept friend request
PUT   {{host}}/friends/66f2830dc469ba88ce1924cc
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PQcACHAII7nhVraI0x1yBGDyTbtvIgzJONh4d6ADNucNmo-Rp4TK6tQV5hrCn8Six4UoEKd7A3Luy2_nGgKXpf8RsGAbf_90wtCcBCwKTUa6owe3iGpHChlGXkIHapuV4jBhDlwLJrp87K7KGWlCrtjRQNLtOPTkbk6tmPC1E3KFwbNvx3TiDuUTWYMFQxi22IIjUe6L6u7Ru-CLpZKjwi7jiSdnpGAX7-I4r78bPwa68cFRlYJ9nNlwphs29VR1MtKK5-3kvYpqgGETBmx5hS3AFE4xG-qaa4bA5R6I5Q5244tys7RE9LHw4vpswIzml6gojkERKs0mqcR91_o7kefKyJjF2i09Xyvi8M8ausm8rsfiL4DeZx58qddWu6fgaG4beO20Cqlh_AjSoJ_Mz-mVJ6U7OBdzLjHS_Lee9nz4qTOasyuK40f06KLx1IC2od5SiokNucZ5iBrmQe1Ya_PCOI92DH-DTPnLIRHV-UbBaJX9lqGr3gDPTYjJWQRjBraDfM2vPpEfvL8H_Z4cSYpmOnUpWg5tTzFqr6z7YqSw
Content-Type: application/json

### Cancel friend request
DELETE   {{host}}/friends/66f2830dc469ba88ce1924cc
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7PQcACHAII7nhVraI0x1yBGDyTbtvIgzJONh4d6ADNucNmo-Rp4TK6tQV5hrCn8Six4UoEKd7A3Luy2_nGgKXpf8RsGAbf_90wtCcBCwKTUa6owe3iGpHChlGXkIHapuV4jBhDlwLJrp87K7KGWlCrtjRQNLtOPTkbk6tmPC1E3KFwbNvx3TiDuUTWYMFQxi22IIjUe6L6u7Ru-CLpZKjwi7jiSdnpGAX7-I4r78bPwa68cFRlYJ9nNlwphs29VR1MtKK5-3kvYpqgGETBmx5hS3AFE4xG-qaa4bA5R6I5Q5244tys7RE9LHw4vpswIzml6gojkERKs0mqcR91_o7kefKyJjF2i09Xyvi8M8ausm8rsfiL4DeZx58qddWu6fgaG4beO20Cqlh_AjSoJ_Mz-mVJ6U7OBdzLjHS_Lee9nz4qTOasyuK40f06KLx1IC2od5SiokNucZ5iBrmQe1Ya_PCOI92DH-DTPnLIRHV-UbBaJX9lqGr3gDPTYjJWQRjBraDfM2vPpEfvL8H_Z4cSYpmOnUpWg5tTzFqr6z7YqSw