@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}
 
###
GET  {{host}}/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7P7avtY0BfENDfVjOCNxJJTYwrkZ7g_rJwJHMcUkjiuaf2v5aqeNXtNyVCee-nPkTMqPyitJfd7bJPGDclIrYcvu70HKr3iP3x6SoLisfHc9QbGYlWQyC1yxGrxC6klrDvFeWRQnAq6UqWWe-92b_fM0GemXAuTEnbUvGgdCRDjCIy7r_62VbThip-cc4IZn6_PIbCN2r4kH1PO_XQPA8c2OamwE-034XfzQICPw4xxxujIrgbVWUZgTcz9IZTwYjl-xdjoq7h8DdNbnV00nkgE7bXnJbvtEyWyDG9IRQnm3Y5jO520MOkQVz2nslC-yn_XltKjoxoLI9j4b_fszNtC2Q-gnZy2W6TTqp4m5E-sNW3CxIKjsyZVBKImJnjmegCVHMRH9Fn-qDJIDP6mDd0cY8lxG5Iccd83T9cS8zkwSeJRKMfl24ROv12YpIbWAHghXToDPMmgNGVJGK0ZczmrRsIx1I4E1H49y_IyZZY0-Ecbp7Ks0k_st-Coc9bzwMDb_Kmnt9FuRO_hH_ZFtBA8F1QQW5dGlukTbYBX-MouMw

### Send friend request
POST  {{host}}/contacts/66e93dac797479d45a6ee439/friends
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7OUXE2oxAilhxmR69d97kaClHnpo8mk9lPkc6wDu3KNbsxN66hghjq5uNbrljViWvPoBzVnW_H08Pq9O29u46g9OeaqDlrFCzShPMXXQ2aULoqLUmdFMcBWmHo7xL54wuQz2lHA4VywMbG5-qAwj-FactLlyvpgfTB2c9FdeRF4Jm0SjzuX95fMwB6_9lI4ciGFVq1VhR_oaKcCLEhWlxGspNIoSNGBbzMmgt5iAGNUXYkOSE9rkceGZcFgZmKRUC1kDKU4GtOi8HWaUUNsfyvyTMjxHHAK_sejzh129ZS12GAWSHlAnl6DwSojxcmKpmP_DA67Sj8MRVla4NJH6swQLYxKwUawy79c4-8K2yaZV_JEWk4-8uwCtLoNIa5jrc70BBG7PSllMAq0OmI0yZwbLfLOevK8UFaTNnWU6GUhOI1V6JJ0pCKPM0li6C8cAqq6VDa5mbE69EuJXoVYSNm9cWR6CQCO9b6F8CtDOBNl-ZSzEUZHBsDyXhiA1AuIWjigdHrmarIMblLM5goawtry72LxTAJFeLXEkfIxu2zXvA


### Accept friend request
PATCH   {{host}}/friends/9cab2070-45ff-40ef-86db-d0a622965755
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA
Content-Type: application/json

[{"op":"replace","path":"status","value":"accept"}]

### Cancel friend request
DELETE   {{host}}/friends/66a3a2b6-8f67-4d8e-aaed-1696e657c0c9
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TSJCqwGmEN97nBjpHQAfcEWIq_TMClfpZLxzHOSNXbgR3rMVRDHSawHGs7iZ9vvanNHvXaeTE_EQsozyzD140NwhOJPRaUBBIGfjPWX0Z4NxmTFnt9Yg3G9lHvv04p0VEXlou5FT_FkGow13Sg96W-KrJNR2qGIHMI-gIrNf537LzhFS5otlaj7uDDW55xiYRzH1Qya6sItmfQeXCZ_RFyMrlGxO4EpxE0ysAhRhJXtKHdV9EdPTi23C3hx6Uxe1PVu42ZI-a7Bclt95JZOHvun_Uu2Y5hM3eEhHrm43Cw9TFGXDXsGflMQY8dNicoXJH8IefpsvblnV5q4GgXwD-FiXxGRZoEh7_jwLPPqq38AZwWAnvpvW2WI6_TrhDE41dxgr8jxtVsFlnDn_s0OzV8JGVZb9nROyodkhFvoe6Nx-im8tWn3MThjYh7pUzIW3rI2wYZ_H-caA6YtwXlRfz1ZKopSMgllE4mOyWBzaoGoANSDDZw2jH41iYbiz_ATbvgek_yiLUXlorSUCk8EYss8dOEzCryxzWfXdwH81sNfA