@host = http://localhost:4000/api

POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint6",
    "Password":"Qwerty@123"
}


###
GET  {{host}}/notifications
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7O5KqVBMmpaCjWIvKhxfD4S_C-y2sur8snX_zpP9gsd2R32MYrdLXIpzfoYoewjB-ruXwacFKgrcYNnE_RKIIfi5KqLhebUVNbxlSXA8FnVHONINT0lE9Nfo1LNuq0MRArxwTxpEyLA2JGG2vPHDNPCWoJbcCIgRY5alJ3kFU8vjh-MP-9qX57FKUIpuXe8gC4sbqGGOVBSW-bkKt59j5MHnDCj2pc2QgcWJlMOzBIPKtQoQgGbLpRfE98AdxFfCHVFLKDUzSUI6mn3mMA9t_R4qin8nKly64Y0Qyuav0cCBZ6UvVGWB2HQQI-FKpD5rxDK_ba5dPhiDHyf2_D08y1IddrtSDEPkKs45HWJsOtYM4-UX0Pu4Mou4lkNM55aMTplxv3aAsGWJ7GeqdZRyAbAi5pnPHvdDGNKrDpgoDb1vHY0IgRCSYhyQaQG1tw2e47vEOFENvjSDyUUpkwO8IqeH8dvw8ta75kqMcjrH6mC3OJdsQXxxLzSiL0mlE_Ion7-2-M7wVWyJUh86U99oE8M2O-_b4mBWbEDZAkv6TV-Jw

### Seen one
PUT   {{host}}/notifications/66f28410c469ba88ce192519
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7OpUD9QPab6QO5BfhDr8gD2EXyXscbkaOz5XOjh_pRfn7J6L545xAVKNmDJQtOEqHszAcztlhEBeWCRXl2Rc3-WapLK8dAF0yhUmofp4ujazRbXZpbQuwxXuB3292Uh8I6-pRAYQGnF6LbOhH6UiV8i56euzdxWDJJVzMInOhUkgk_cftHPhdS_JpPgfM2Xy67zss3_KXizXMwYEHqfs3OQuHUzFFk65aHHLHl19cB0UmE2GqjKcP4odknWFaXYQ1X9M9g7XUsYlf5PW9deI8sj_vUBF5oUazaa_HT-S5-bYF4DlGYK2N1ev7FO0lGkv-SZUqQ67rg4ssYWmiopDDjricdtVt9DyDT7IsdBxFbEP5daPMr7mOP0mJu9F3s7behzZoG9YhZNwoMRp4A2_LSn6IyBnnjb-pIpi4Bf6XM84gNEq1U5J8zCiYq1OjF3gJ7vHvC5u8mpI29EywpUfjxdrzBejAKgid_6SDUFVRLiuFNrp9g2UlRklW3-SzfW5tdXSS0howADKhuBQvz2_Z7ibmYaRt5rg2L-Jf8qab766g

### Register connection
GET   {{host}}/notifications/register?token=1234
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Ol_imak5lWv_rm5Z7FUvJswFSPD3OZ_Q02MX9FDEOhbu48H6FWMoj_sKdjdPwS69XD3PbDFcOsdvZXZHViEuQSAmCmeinVlNLGRMr2PV5UyblHND97uo-P-bp2kZgP14Kb3g9XQGQfYfrhFVfe5UIfcdPor-DVDslj9aZPH3B18Remch5boUfRNCQW3qThFEFfTebFg0qPpbPxxhZCr74CiQTkX0se7LR9XYnzWQoiBZcxWkoOAc1NmsOOv3e-8npUBnjj-Ij371FDaWokxoQQKWx1EU3ifrOsQysqfdNJ84TsNOmr0-taahc4U83TADO5Q6kY_7NIbYFYFzwBMIKwToW3ZtPEinpOSAZXMPrtRRm03NXiAknvNlFFiD7H4PS5dJB5K-m_O1Z8ojGlz_fPGWHWSDBMemwhmlu4w_DWzNk6G8msnt02mpIYFp9h-RtUjg_Eil7vRUVQTfKcuaAUbSv1jvyENNmN6ynL0uaR7viSPXYOISKy9NW19vir_h8UGDXfvOcs1IZXdkHylHDj


### Seen all
PUT   {{host}}/notifications