@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}


###
GET  {{host}}/conversations/66f2e050bf6c58771c941076/participants
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Oy7hrfm7jDk-vRCVJGpODHPox7chKvYpDYQhiTnMe3fGfs2H5Azchb51Qs518GTaDZzuyhKnbc2gP94CRBOUGJLuvnyfqSNF42qDZymGwylBKFOrTyGhh_LGBQ_GyE1n4dPKsDnJbj3EXLWczWYGQu_TSk3vh5cbotUuW0XxCQysTS7rt0rDaLHW4l5Uq4Bvhrnmd_jgOXqPdQ7NQK8ci8gGac2BldAFlapGangwnyLnrWlVC1QSRUmidou4BgeYfZJFrKAZAgnh2tsFqfd8czK2rs9jyiKod8fLd6Qq5eKg8DZHeHXgfR5KT7ubXosoGD2Qmn9JpqcCN_z6FuGL2GSdDlLsQSEkOAu_I0jeV9hsXN-ovy2My1EULY-Gtz7swvSucr2m-Jm1tAqABO5QurXa4zWDLYqbo9YUfWWhn9-YmMdNOJK3sRhNPSm572OdJuXiuDWp_x3Pk4KBfAY4x5-u4vdednjijM0pXmkvzhmEiWM94g6W5FnN1hqfZZYH4K8vISnltwQFwOlwayjirxkS8B2g3TwLEi1MjEKC1a_w


###
POST  {{host}}/conversations/66f28e16cc3495638bee8764/participants
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Msb6ZoRrshpEu3o6xmNncAxg2y-9xppazc8HEoyletYCNBwa_Z8fT7mbLtgEAvB3fOiPfqEvqtilou16juBrSwgjgAjxd4T3Qdx_gRsC2YMiVlOXv5F5uvtolyDSE84mkCwFAT-gdLgLq8ecDjUCs6EFXwE-HysHFqDeZEJzvSnZCzBB0RtxbYgX9sjAdhuMBFYK8cNL4dM1QSWw1YwyWIkQTCoJuMioaEgBAjGBeZjVcmENiuBEi3cyc2bEaKmypCxtPIS1isTFew9Olbu9Y0mksjOYHyXU3h-TBuMUh7VRRAHbSQJzeV3-lROIC06OUMmqAXJMYp3cCc41JZgqPeTJ7diDvH0gyP81l6oUtBL7LnVywm-PinPLH0hHxHe7tL5A6Zm-wHcAqavcfY2aoAUqDdrztssTIfvypPXdPDPVG_6-Nad3mQCJUNjPQnNujwC-HtCiBLGJtZpj6-Gz3eTirdQ3HGloOF2JeL7Kvt870a4S3eU4irPT9XC5bvsuPfqTlE2fRQRrZpBC1Gw5aqcvksg7ccOWf-IQyLvdfo6g
Content-Type: application/json

[
    {        
        "contactId":"66f28326c469ba88ce1924dc"
    }
]

###
PUT   {{host}}/conversations/66f28e16cc3495638bee8764/participants
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Msb6ZoRrshpEu3o6xmNncAxg2y-9xppazc8HEoyletYCNBwa_Z8fT7mbLtgEAvB3fOiPfqEvqtilou16juBrSwgjgAjxd4T3Qdx_gRsC2YMiVlOXv5F5uvtolyDSE84mkCwFAT-gdLgLq8ecDjUCs6EFXwE-HysHFqDeZEJzvSnZCzBB0RtxbYgX9sjAdhuMBFYK8cNL4dM1QSWw1YwyWIkQTCoJuMioaEgBAjGBeZjVcmENiuBEi3cyc2bEaKmypCxtPIS1isTFew9Olbu9Y0mksjOYHyXU3h-TBuMUh7VRRAHbSQJzeV3-lROIC06OUMmqAXJMYp3cCc41JZgqPeTJ7diDvH0gyP81l6oUtBL7LnVywm-PinPLH0hHxHe7tL5A6Zm-wHcAqavcfY2aoAUqDdrztssTIfvypPXdPDPVG_6-Nad3mQCJUNjPQnNujwC-HtCiBLGJtZpj6-Gz3eTirdQ3HGloOF2JeL7Kvt870a4S3eU4irPT9XC5bvsuPfqTlE2fRQRrZpBC1Gw5aqcvksg7ccOWf-IQyLvdfo6g
Content-Type: application/json

{
    "isNotifying":true
}

###
DELETE    {{host}}/conversations/66f28e16cc3495638bee8764/participants
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7Msb6ZoRrshpEu3o6xmNncAxg2y-9xppazc8HEoyletYCNBwa_Z8fT7mbLtgEAvB3fOiPfqEvqtilou16juBrSwgjgAjxd4T3Qdx_gRsC2YMiVlOXv5F5uvtolyDSE84mkCwFAT-gdLgLq8ecDjUCs6EFXwE-HysHFqDeZEJzvSnZCzBB0RtxbYgX9sjAdhuMBFYK8cNL4dM1QSWw1YwyWIkQTCoJuMioaEgBAjGBeZjVcmENiuBEi3cyc2bEaKmypCxtPIS1isTFew9Olbu9Y0mksjOYHyXU3h-TBuMUh7VRRAHbSQJzeV3-lROIC06OUMmqAXJMYp3cCc41JZgqPeTJ7diDvH0gyP81l6oUtBL7LnVywm-PinPLH0hHxHe7tL5A6Zm-wHcAqavcfY2aoAUqDdrztssTIfvypPXdPDPVG_6-Nad3mQCJUNjPQnNujwC-HtCiBLGJtZpj6-Gz3eTirdQ3HGloOF2JeL7Kvt870a4S3eU4irPT9XC5bvsuPfqTlE2fRQRrZpBC1Gw5aqcvksg7ccOWf-IQyLvdfo6g