###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  http://localhost:4000/api/contacts/info
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QkdX5HbOZ19-nKnvaYdM_V_etyIjBmLSr6XmlDfR2pRFZJ6Hx-MW5izZoLu_6TADfBzhbP5a25M-gTd_GjucGvLn6tV2pJICCnDZ4PQ0PI6eDr6Anq1ko2so8sxrAGnVUQoOv7OFVei3kUY80MXzzdSIuZAz_zfQXUAVMjv4f_CF-b6jV1HJ2MFf4_aVG-TDgcol5s3T11yrxUJ9BhiiAW5W7rvhttuTFTzgpapbMWQzi9lpW_E34BVcPpcrh-W9PZ9zcZL1_J4KgpRqalLgiwr9YHr67bgsgMVr53UFaBDEqcef0eBlZmA4ybLSc96TfOqhRhYSiZWf43myI05Ekr8a4DbbXYlYIpyIkMGL47RLnGwRXGhhzfpNutCEjcybao2xTX14jDVmyHARQ_NTT8k-LB61M6gQ0EtWoU6ZCFMwvJT_gB959rXYRp4uGUkgUo6LxkepD6pzZXOU_1kGCe-xjBvmrgoPDy82DH832Q56zqQaXiG8oBpGpLX1VqmjJZeFSuImBaVZTFfNRF8e8rZpEFVwxYgGtwKa67w9wThA

###
PATCH   http://localhost:4000/api/contacts
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QUWzSYIXSNQEtLAK3_1eFiYTbNlTEbWP3pwiVuaakGVmswvDyJSqmarpaVvJjE-TkaiQo57QHz6CpQ9BMIpt1K5Z8EPiahQalJ1VxYBTDXkuT5oLjPzdVNt4B87zpOvNiu6UqOydN0vRGjn1uKu_AxWtpZ5RUfv5FMs4maHy0jDmeYoj118r_rKkismhQKzohBWGTkblq6R1kgexrklxKaeYqfCjHY-4CJpopFnqhSLl8-BHpzI6JukpjgGsl4W-YkTyty9sHLyWpe676YnxjK4_2cPhWjirfs10ERBOdHLFUdkhqnBDDwgS5lTy544i79h8X4ZHnLl6ZfCeK8_ZgMdxGEb2mbA-LUBXVVIK2O8l_bJcrMY2WKf3Ipv5OaAZRoSbPetLi8EJgEYISaM7ZQ6hqEZdzazGPAidxQ_AdLah6heoB6kdw9uMJBvNetaQE-fhct5710kG4mrnDXG0vDYQCir0vK5VNfGL2zE0IrrEHjUciStVPPPBtA3ZCAS1mp1_rSsS7QtT1srH9Fj80EQ06-QxyQKomOOPpnpfw9lA
Content-Type: application/json

[{"op":"replace","path":"bio","value":"welcome to my world ^^"}]

###
GET  http://localhost:4000/api/contacts?name=tri
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S98GiWzkqj6yECD_eAIb7Hnn9esRzApLv6D1frCPwVnVE5okN-zjeDh-_nm33c1vv1b_wewZ393gzdV6vpENEdLu9UmZLb0tekjYJYZd1wAecOvCyzrzipgu_xD5L9fjcKz6WBrxeQaIU1RRLRyLkNt0LhhRNvfUg7KKg3J-_8W_bOsXNnU0LVGcpHw45x9ri1RuIcJtqFFQ44mDmg9wuvplKNjhtYGpWAuAV37Kp97828V9bPJa_5t5Iwtco3PDaen2Vs0S6WWOhGf5iC20-dSEdu7sSGc7U2NiQXERPmCEDdVNPaSIZ97EY2Ixtcmal9P3eQzvBIpgVk47meU-ZyBkfI7cLJYvjPqoFo26linZZ2mtB5RaIEVhHTmpKz614LQ1zzadwx5tkb7Eps5Gq_dEgcdNFhNy38hSEtzwJWYmBmIjg_y7ZH0GXo2LhM164Oh3Sp1NR8tS3RyYdv4z3dP8fhv58sHf-VXwBwi6WTNt-uD5AB7ZeabnmkSigKN4GZQhkri0ryUnRM95RA-wxUHbYumbbaJ1P83IJm-sj0xA


###
GET  http://localhost:4000/api/contacts/35b3e2df-b853-4cb4-9a05-02fed171fe3e/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9STGDOBNq0RK0GZsjueLybJvN1EIK2vQaxRlcY_jtcwe4mAYuivVtC_ScJ0E1PDaXbiU0bPX86AMpdZJGkHaC2GlFLutcIXx9wbZBTYWFbS_4VE1tafAOIP2bsyhYMM9cut4_d_6DjY1GEBvlkEuk3F5ZqaOIRYcWvl6_VwH6rIVrj-bvaVbVNMfwDH5OufkhgT-akpNgpW_M7QT0VawJMf8C3zteOrLD-bOyOWhhnYFSW9YcsU1omfvrrORGlMPfR46450WMXDkCmh24LZWf9StvmGOeWSVuma3BgrW_mMH-E8RFVfsseUQynIUV4mCzShCwtWQJHfTgzckaySfXKCYdNSH35dzQePTBBu2Q0T4el-ZAUgAWoQBEtQe5bFR5EmCZa32ZLdbevzvAAEZRaT54Kmfr4whJxI0cAOFdLD5BQvxZbZ5JhumwflxU0UohTDKSS57iOQ94YxNT2L1RSN-rcgDyayGRlVHEn3-7Rvo4aO3GvmYqM7vCxPnj2rYYnWFiLKBckbae9AVPOcrdm11Wgyfp-CIe5NPYJ6CQO9Ow