###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
POST  http://localhost:4100/api/users/signup
Content-Type: application/json

{
    "Name":"Em yeu",
    "Username":"emyeu",
    "Password":"Qwerty@123"
}

###
GET   http://localhost:4100/api/users/signout
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9SYKSugQwj9SQxB0AmJwWC6fhmCIyxHCT6S6rJUyUc3BKJgvzjE8PRJH5X-vurxSRdUx2f1Jy39eaSRV-xiI4kEkw1cbhO16SHAKh4e13m4Jl7gzRfi8vYH96N7TWyUHBUmOY6fKIQocbEyW1LHn2yP1jdgaGTIy2aWrmkwhbtfflB2sntTg5iCiam8i9X-6YGIGF1TZQ0_4fGgZkXpUQAuJVdJYewHxIqLiuqIFIomQorsDUgf0JoHRNMvx2gMmnxdwGjj3AeZy-w6E7xJkMeX23ecpnOM-Ok9Yy_rlKRnHfjLut3HCZMJSZTk1E8xpvyxPJiU3tNR87cvQ15oWQg3NkGDYRxZnmXC21SRtdFueDOu8nQ8XRTdmRok9r42QgaFWXYAXg1EU3lM063Ji6j8gU-5fwYpuzSA3seppT0gOU2DnirVaKKcrasA_6nPVd4__oC9tdD8ehuie0bkYQ9NSWlxIG9-C0pRK7saaYrh9MQrVbxXILYLpijrz78GGhEaFctA3vFDPObtfgc4y-_uO6dLj-UajCRo65Owacjd6w


###
POST  http://localhost:4000/api/contacts
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}


###
GET  http://localhost:4000/api/contacts
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S0abcBp1wkiroHdw8CsM56yD9UVly7whGKGk60AQ5eyQHJE0wvIQJIvVd2TtOSVPzyucGFWNCSEw8SS9etnrc1eLCmNbHQWrwPLBskYbWmNxov_-cs8LttgZXmjCcPgYVDM6PrbVdJSEek5nphvE1a1N6GkSOO_jhe3iz0NIghhCPuzLu-KAS0hcyjwFxMqszxXtjD68I67C_jL6YoMSvSRVN7IcMfEew_shhULAXQDnmOzRuAOOcYGuI-nTrw1ax25nz78DYgJGcojGT2nFsw1pMqoAUGVZaTm-vaMU_1n75mm213n-Rp3--RZs9h2RsnvNTYl7_SU_e2XEQgjlYCIMbVmKO85vSRUuKaqzmLsAviZCVcwu65YufvE0SmKF0jKuF4MVumXuHgn02-mJxp3okGsYRAUPVXMHygc9ZFULydUlNMLurTEMRtMvza8j430pQOyZOVZc5UKvLZAfs9T57sSpNGbFjPzYJJD_k8GPiuXJRdKuu1fbU6caKxftlY9Met15h5DI9Un1RzZ6_4YV8NnPv_f3SD9XAh8zl2ig

###
PATCH   http://localhost:4000/api/contacts
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Sm4-Ehj2WeYqFAw0CVB4MfVioyhcdp0YTwzpzlVUjbwxytHHfU7GD2PE8DslhR1Y1DK_DGq9_mYW-TOeuSu99swVfsGko5DxRsqP_OT5v4UaToEeluo0LDSSzJ0i3sF0uRYSkw2vJQf7OMRlAHlcl3gCv1BHBCIBvhuQrT_jsWG-DdGh0nfCTEkYi47SDWxPO53Xg3wGD9SFNvzN9eGxL3UXf6VfWckroRUpWL8hYrgIF7vbt06pHKxzNUqWit5nPrRE2BXCvtABjcD-aKEQ-dh_SPbWrn_HlqR7bWK3kuR5Fj4Y8Cjucy7zB48Mg9fF_rg5OJuI_c2GKliWIU4k9GKnkIaQ31OmAWQxi6SyRRwMhFIfx1PD-hAKK8ji9aIkl650KmwP1qDWKpPFlzAeql2ZqSq3Bhrg8llJm3RZrhpLg4zTUoKikH8LL8ZpdkaO8-6UcUZuXSXd35rsI3mkxWymXLKepwPbG-VkC9tCO2T2AGeEndU8ZLwBnxAgyMmyFCszOjT8qb3rumNa78su-ltgCgAfT3_bNhZ1QMzmjbOw
Content-Type: application/json

[
	{
        "op": "replace",
        "path": "bio",
        "value": "Welcome to my world @@"
    }
]

###
GET  http://localhost:4000/api/contacts?name=tri
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TavV-MX11ZZlOUEnBV_LtdDgWoBZiR70IlYHtav3GgVKlEwF9S1Z_y9ntSqT305p9abqm1yp7sqKMaF2JAjQyiT1NCjhricGsB__pJ1ZYC20rIsL46xxuUADCLS1JE2eqQRjZwxepHHiyIwysbFz0gZfYgxRFaYaRxHrU4cRGdvKXfuTobVu2f_KVzJtW-yBD8fSjLCOryioNjYuPfVPcIoo0aG9M0IoTvJ2ltQZzCh0FhWhpFWlJYzHEK4AA78pyyV9xM3LdFNo8JtUBS6ToC-bx697fh_MFoF3Ix_4xBOvdG4xlLZwAfZhK48FbLJFOh8psZwyYhSYhU2pN97V9wQJbEAmM2hvDcK4u6xULgzy4RIVTZwwE-aO0u5fhf488FWxlOnesvw0184V7qsC-stmm5IDJCW5ZCfrh70e3wfqsot7sCm3sIOLfd0GfE31jdsmDhwox9j2R9DNglKJQo6Rp8W6FcMmZyJsgnz0WH9F-HWfzwJBfA0krExqIB5_LHZiN3-5gb9a3vxHKtv9pKIGUAI-CAFos3EaOkqThRtQ


###
GET  http://localhost:4000/api/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q6GYlPqVuOQHmbC84D2clTBG-crDAe7n7lx3l9OgOadEwyxEYtbeDyfyfE334aKMT510jH_tQMkqWUlvA9Q0uXso92YBE9k4jT0HpLlMwmMZNgA34Xk5WqXG3doFXk7vbmo8oaVW9Dp8m6zjXoqAzrWwnv1SI2khp7THIDW8LUA3l--x_3a2RUZjM_Fw2AMhs6eVaEHxKR-63c6JhMzH_1CSSFdzlg2Ja9JPOObHGi3mkuN8Qz1kVilQdYAZr3ycuHThrbSsMgt5uYTFaASPKz9sGuH82ZvvjPj-2X70Ay5n13Ts8gfsNvRh3g-9ROehMdslDSf1hbqJ-mPeetkVNLtDfOAotLA5IeJ7NeGw31_RbRy5CEfjnJKRXVvIWU2zKgWxKeStotjgaGygLsCH1Rt0982QCtHJ6OsF-UCyD1aWcE21TlxgTxWr0ES867nw-nr_H4Mvv_WVtrSUqRwSr4mwCZPnYHRqx5XEku5Q4wU32BteQPQ8jn5vuFN0zB34ygGmkqfXsFq855jUYgMB-b2gkoFU1AK4kQmBjBWu2KRg