###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  http://localhost:4000/api/contacts/info
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S4mJ0eTRzNeqxPp0to_xPVEiLSa0yNAYN1fvYTbcCb6NGT3JbbxEDmv7utV0-GXgKjxYURADo8K57H_aTi7xseYuXn2poTEhFtarSaN0ZFW1x_RAZLChJkiC0Xv3OBDb_xoPWVo-h6m3dnyQNCgp2-uDRVUr0YzRpa_f5NePIfbM8D88Bk_f3-Z9UJUzbbfWSZoU1WeNb2q7eneTSkIcmzpytx8c7GPFVF-wWMHUXBC7qfDGDdOEYB2Z5LheP3FsYew9dYzI6ZyScKClVgzjl-yeVuGjzay0FtZEpS25Cu9ZzCOE4rkMR6rCfCs0B1CVPUbmFzkOsCNZmK6qwVAGeuBmLLa_ShSAC7XqpePZqzmHJMOmhCLRRf_dWya41-ZldNgNovv0sv0HoycK8MWp0_X0JQb67sb02vn7qKF_42pr3YFv8aBTNa7xBN5vwrcF9geOgfgE2y86rBgwd-6Xwml9UikG4cIoW8lyK-LXyoiFad9fFhIkmEkZ2eTYIP8L0WJCouh-DPjlKvxfrHxJZshrEs4BchjQXnS4gNykFXsQ

###
PATCH   http://localhost:4000/api/contacts
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QUWzSYIXSNQEtLAK3_1eFiYTbNlTEbWP3pwiVuaakGVmswvDyJSqmarpaVvJjE-TkaiQo57QHz6CpQ9BMIpt1K5Z8EPiahQalJ1VxYBTDXkuT5oLjPzdVNt4B87zpOvNiu6UqOydN0vRGjn1uKu_AxWtpZ5RUfv5FMs4maHy0jDmeYoj118r_rKkismhQKzohBWGTkblq6R1kgexrklxKaeYqfCjHY-4CJpopFnqhSLl8-BHpzI6JukpjgGsl4W-YkTyty9sHLyWpe676YnxjK4_2cPhWjirfs10ERBOdHLFUdkhqnBDDwgS5lTy544i79h8X4ZHnLl6ZfCeK8_ZgMdxGEb2mbA-LUBXVVIK2O8l_bJcrMY2WKf3Ipv5OaAZRoSbPetLi8EJgEYISaM7ZQ6hqEZdzazGPAidxQ_AdLah6heoB6kdw9uMJBvNetaQE-fhct5710kG4mrnDXG0vDYQCir0vK5VNfGL2zE0IrrEHjUciStVPPPBtA3ZCAS1mp1_rSsS7QtT1srH9Fj80EQ06-QxyQKomOOPpnpfw9lA
Content-Type: application/json

[{"op":"replace","path":"bio","value":"welcome to my world ^^"}]

###
GET  http://localhost:4000/api/contacts?name=tri
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RCQsafhVThrZYaY75PuFvNelW5Uv0k1bCpiq_1E5ZFAjH7Se0-Wo9n12zbYEQuG7ApWh7MwbG7Uo46l9WJ2tG5pa96VifiUgC2S-WrsbXDQR0HsASsaMQ2XbA8_HOKPOtoXEYveE1rEyf9tKubh7aUPL0BzyibrweZRUU3QV3eJu1BNhgTbkZVz1ZboNbHGbN40Lx58IE7_aZHvjskeI0ZytmcygOZFAya4UcXwmhpgHI1WA27AZThSwE3_21Op2tFxPstjYNcGGhQZ6jxVVrHCDj9OHQfxy6ZxHaWNoyhoVbqFFyI5DgYICiybp4IQTJ61eSNiH4LbF37rsz4EJY8S9qRD7aFbZT4XtCcUV3GqqpLyHNgSrnzdoFRH5u_shLEVXHnUE8qlStLeVeRVZIVyihj4kjuHmwfvCTAvl-ETT7BL4m_4PtBReLyVYRZyPEtJntkZyjkKDlQns9U0Nn7iKpYBjjwfZgVSS-8WALngQIQwE-ll8Y0vfAaCURTxAKjgWgPqPs3c750esRUDPdV783SMRe4XddGvxpHyoHsDw


###
GET  http://localhost:4000/api/contacts/35b3e2df-b853-4cb4-9a05-02fed171fe3e/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9STGDOBNq0RK0GZsjueLybJvN1EIK2vQaxRlcY_jtcwe4mAYuivVtC_ScJ0E1PDaXbiU0bPX86AMpdZJGkHaC2GlFLutcIXx9wbZBTYWFbS_4VE1tafAOIP2bsyhYMM9cut4_d_6DjY1GEBvlkEuk3F5ZqaOIRYcWvl6_VwH6rIVrj-bvaVbVNMfwDH5OufkhgT-akpNgpW_M7QT0VawJMf8C3zteOrLD-bOyOWhhnYFSW9YcsU1omfvrrORGlMPfR46450WMXDkCmh24LZWf9StvmGOeWSVuma3BgrW_mMH-E8RFVfsseUQynIUV4mCzShCwtWQJHfTgzckaySfXKCYdNSH35dzQePTBBu2Q0T4el-ZAUgAWoQBEtQe5bFR5EmCZa32ZLdbevzvAAEZRaT54Kmfr4whJxI0cAOFdLD5BQvxZbZ5JhumwflxU0UohTDKSS57iOQ94YxNT2L1RSN-rcgDyayGRlVHEn3-7Rvo4aO3GvmYqM7vCxPnj2rYYnWFiLKBckbae9AVPOcrdm11Wgyfp-CIe5NPYJ6CQO9Ow