global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using System.Data;
global using Microsoft.EntityFrameworkCore.Storage;
global using Authentication.API;
global using Microsoft.AspNetCore.Http.HttpResults;
global using System.Security.Claims;
global using Domain.Common;