@host = http://localhost:4000/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  {{host}}/contacts?name=tri
Authorization: Bearer CfDJ8Ewr3uB8c9ZPsF82A6d6P7OCIOuKf1pbHeLXv3vCO52Rv4mYHQSeauMqCZXQyccoJfGmPatKo0GCQLlZvRuORV8AJliPJ1YeCS5hg7gAzShQTyKuZB-wkXdjpEiNSQ4YfdhjbX9zCbnmlOjBaqmysi3AZ1sanF9IQAaKHdtG6SzxinFG6vW7r9_lbTlbx4Wnl1Y-rWXxtKCEvdvMBF9snwrmJixM1kiU9UQi5GwJdR-h4r4m8nNXGU37uVgRWJVmLRjgGAzJWx3siR-nlhHNRbN3SwcEvsG441EIcaCuYtfzjYu6SOfNRMc_p78Hxw_m0fEj2596wZ1GER4CPjfJ79AVH6uVDMqLUuP-6Lh3q5k1tuBUds_lF7sFoluJ2luc_LYTz2HsbHmPZaYlRHrud1o7XnPLvTfioufhbZFT-0todT-eTH4lfsFv9lJKcAb-GE6RkZhZCl5mJi0YRjhWRwjsKVROvCd9HARTeiKQRoyywnbv95OsN30BZUgwZ2Np-Hw3wPQ_Ni6CgOQi5nZrBYI7PGgZk3ffV88s6f4CcWa_YoIBfn68zX23A43dx8_0ig


###
GET  {{host}}/contacts/15c43b14-8148-481d-8f0b-5cec28ee8764/friends
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9Q6GYlPqVuOQHmbC84D2clTBG-crDAe7n7lx3l9OgOadEwyxEYtbeDyfyfE334aKMT510jH_tQMkqWUlvA9Q0uXso92YBE9k4jT0HpLlMwmMZNgA34Xk5WqXG3doFXk7vbmo8oaVW9Dp8m6zjXoqAzrWwnv1SI2khp7THIDW8LUA3l--x_3a2RUZjM_Fw2AMhs6eVaEHxKR-63c6JhMzH_1CSSFdzlg2Ja9JPOObHGi3mkuN8Qz1kVilQdYAZr3ycuHThrbSsMgt5uYTFaASPKz9sGuH82ZvvjPj-2X70Ay5n13Ts8gfsNvRh3g-9ROehMdslDSf1hbqJ-mPeetkVNLtDfOAotLA5IeJ7NeGw31_RbRy5CEfjnJKRXVvIWU2zKgWxKeStotjgaGygLsCH1Rt0982QCtHJ6OsF-UCyD1aWcE21TlxgTxWr0ES867nw-nr_H4Mvv_WVtrSUqRwSr4mwCZPnYHRqx5XEku5Q4wU32BteQPQ8jn5vuFN0zB34ygGmkqfXsFq855jUYgMB-b2gkoFU1AK4kQmBjBWu2KRg