version: '3'

services:
  setting-api:
    image: trintdk/setting-api
    container_name: setting-api
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    depends_on:
      - db
    ports:
      - "4000:5000"
    restart: always
  db:
    image: mysql
    container_name: mysql
    volumes:
      - db-vol:/var/lib/mysql
      - ./db-vol/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: "CoreDatabase"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Bangkok"
    ports:
      - "3306:3306"
    hostname: 192.168.6.11
volumes:
  db-vol:
