@host = http://localhost:4000/api

POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
POST  {{host}}/identity/signup
Content-Type: application/json

{
    "Name":"Em yeu",
    "Username":"emyeu",
    "Password":"Qwerty@123"
}

###
GET   {{host}}/identity/signout
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPgwFBARK7phr08Mf24dzaG9VvUnBNbP2pM21LMCPneBwenu6jcYruMOyA5AkRuSxieAvRsPg-SqSLdu684cNDDSPcBoU7qIsyemTw7yuvbx0uQrjchWh_NszIgYEDxtCzBvYezKysDa0DxaUv6_k33kWhd3Y_lj99IDO4IxMJ_gIkiDjdTWtWrnkyEveX3Pss44XqGxEia_7F_LJaxcRNfLjrzkQEcwjtdNb1fScVBDyWCM_qkMpSCuy1bWUhm_5JfaAr_NTHCK94l5fMGC00N9MsUHvkcsHnYEU9nl2RLJADTlBYzOH0RJ1XpBbYzlzNBMVCHY3u1Y5DmWzky25_7I3kBX44GdXQzWk2LYJTaI2aQM3-9CyBB-WKQudzInq8vLlXbPOoLZ4mbR-5Cyf_g3wDhWzyYU3Jo8HV3ViIqlX3UCqpzb9_Wjerqs8quFBLfxmcHiJdXpgzw0d82KeTY5kOQzjXVp6v1Ws-3K5RY_jVjda5vtKog8tPYgIbccYF_lqb9XbFUXnGR6p7Pr5XZxaa4TUgvI8T7xJqR9PQ7MAg