@host = http://localhost:4000/api

POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint9",
    "Password":"Qwerty@123"
}

###
POST  {{host}}/identity/signup
Content-Type: application/json

{
    "Name":"Tri Nguyễn 9",
    "Username":"trint9",
    "Password":"Qwerty@123"
}

###
GET   {{host}}/identity/signout
Authorization: Bearer CfDJ8IE6k77TFy5BnhYCqdQ4BPglBOdoE4Tak7enigva0Er2UY08GiT3JIuz0leMCDIC9JkHB89gsGnNMECNecXxY7XfeMJJJkElArLyDptSCIWgFHGPIQ4wQ-_nn1E1A0RQKqrHoaKkUif47Q5WerBJ9UAsaVEluhR8avO8qoZxO0tINdiOUME1shlV4uJ7L_XXvw_HiP--igKM4MHJoVA0qol4uADsV-ul-BK_MyMvichqOmEe3ei13UThYfPN-H_gL8_PV7fMNTbskWBcNEqLWcVArpVGNkNyOGE2wMH5rjgyXa_ImwAIw1unMr8pJSTD5VXpOPSFP4eqNcX3DNUjYIf7oV8avnLucP4-vOxJBqPU455m5k9msOT21ah-d2q3qknWcMBjMY78jGYvmIvTysF3xp5Bj-W1om4EoyQxlduiVugRW6chQA7kgvyMgpOxnhzLPifPz6KN9frifHsB-zOzs25iySywrEAlStDGUP5hZZtqGR5_ncSHJt9NWt5CKeCdaMsKdBrs_ovcqUV6_7EIlyXCRkjvJPIB9hBqJ-ObnWF2EthKQ7reLiDs5IUOZg