POST  http://localhost:4100/api/users/signup
Content-Type: application/json

{
    "Name": "Tri Nguyen 1",
    "Username": "trint1",
    "Password": "Qwerty@123"
}

###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  http://localhost:4100/api/users/token
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RjMKgYZQiVqNeFOspXgm8OyowBZ_NajdYJYn7odVCsHoZViEbwz5A-eCCOCVUCVT0QZq6FUSNSnXv-sFmzIk-ksU6o--xKQhYVXKily6Hq_sWck0RZayD8iM0vnyaTRDHgebxUwvfmmK2_PYeT1jBqAZyx5ZACOvQV8b50nTJRZx90NeLM1JYgp1Q97g8dLvYf3z8_gHt7AYfC7dkUgYKgF3m__KRvqI1UYfx5ESnLPxZZXOhOfNks0W6IK6YZ8XmzZan_3xeJLSVnJs5X8xhpwrL8OQnDBy9CK7teDNsbfRblIOXsZIDee_As-cM0PViWS0iZKbGOaknF1TR8ymzJxbsiCr0pgeOKGw4cNo1q5PRzgmtteCurseby8JDTGTrD1Eu6RoL90w7g3A4dMbweYrj5RzHYMrZRrMvUfwxohIlafW3pLDC72218QgPfo5Qt6mxkDuQ2bLrw5VfSBIi90l5DjdwSlhj2qF66GHo_Ui5WSS2hTxgbZv3DDNHnhdyXEGHAWNVNbIYkw-M65qmL3mwCcjH-HC9KXHxtI_izLg

###
GET  http://localhost:4000/api/contacts/info
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RYUvTRKU20ZX218NQe2RwWE_2eO_iaqrv_diYq9DtOXeqVviTK39wzJuTfLKqYhwSJ0wknsHOZnJLT2DyISpRSFiMS-J6mesKWFn-P3yq2zRB_jgX84PByoW-YHFNRYIjLskrFA1qDmbNeBlJ4CCIFOuENqVPqUBXLg7HxL7oSoLiKNtzkTrwORJWpwzuzv1Vw7l5RnfPwrX-EcLQAAzsuhmHEn6XOQsumgLieOVP5BhVVbGxjZxmct2yX2x3NPaXccEjXf0c5NBc7DDBvfTDxKYJB8lMwPbsb1xS6loIvJJw1xqwwbOjK2hYE0eGY97MYTAj8f9Zz7rSw8pRKJxce4_93i5Zk0DlUVPiG1faoCAfT24pPkyDbNeO4llhlM79P-yqwQ5f5kTwcRBz32TGX-oB9ZeX9Lmk2PxDugdm85KDLTeKTBSTIJ1KfcS_dpW2If2yGP3HXVFu6ZqhKazMnW8xPPG7n-j5ND9yQ2UKIggsy_7X1INmMcQf2ggznOr4j07FcnQn3k289cSbRfZeaamFqA3UkGQMsX17pqWn0pw

###
POST  http://localhost:4100/api/users/refresh
Content-Type: application/json

{
    "refreshToken":"CfDJ8CPzuFnSsq5PudvkkW85E9QCpgg8zyKE4JRNoZ341lrUJz71g7ODvul3e7t6wDlcs845sysRUqsKkhHJe7Z2M2tlTTsAj4W87NMOugQ6jjbkLam-1jM2adQSZul8rugtHXVmXofTWdEesgbvxt5e9-EB2e0PTCl5kEjSYH4BWx0acmUp18jwYsBShI-pRyfsNnPavq0VsXaFsi44hiUi09RrEt2elFgVepMTA7vFwtD9eIHPoNfPOBUoZweeM9wqoHcs4ERjZTR9t56kb4M2mLzUC6r-Z5MlpouzSq7giYG6uH53NFCD9KPcmrL3VL8a5XGpWahkNRXwP4cLHRyBm777DqknTO3BzePpOHmrZmJZhxWUNawki66GeXfSchfGc9O_3nuLQ4aUgATSCOsiqgeIIomq6ohjSOi6HPTo5zSZvmyAnRqpifLYlxkXtxfR4sfQFQyrIxh1zn_EVT91djhvZ_BwVH4zLSlTPv8jfYhgVGZXx65CCy9MLiIHq3tdRLu_08zdoaQ0jkMhN1NqL98h2iffsqgWvl41kyVxgww-fcOCGENPLaFFVDE4SxlFiA"    
}

###
POST  http://localhost:4100/api/users/forgot
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@1234"
}

###

GET  http://localhost:4000/api/conversations
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9T1Fdmv8qwNvvAxIPdPIoJYICcT4ayBaavC-IDyoYlfXYBIB2-xQiXjDf4TWpFE61k_8ikRBxHpp_ii9utdShGnU2x10zBdiGDHu06Ungl3n9PEF2QClKL64Q8icXlz709Bf9w-pDrTRYlu3qRsWe5MmWQ-C48wy8VaxGVh2fhlbRSUuHvOtfCz3gouCreCKaHBs47ca2X6wk2L7OlHMRLQkMXYJVaBF8AwNeN5PSvDHr1OfM9TC-kI8xrC0tsgGilNfaUhFefd2wYAuEeYWa4-aWfDuauuVznJADrb0GlytMCLo5C7md35o57DP-lymdZG0FP7TmzxQdtpucSvazDoYdUvbxcp2Dyt4XkBsBiIy7sPucWkZNTClsEuukCwhruUDzx_0VbpCxz-QIDLtLDXUMPH7LXpEi-wg3LsamFA_fDIgvFgTDI-sr2j27DRc0gkrcd_YbSVq6_zKi352Gi84FozovbRJn33o9rhXA1B31i1OiZAAjx51XLsAYitAOju9S6LW5jyk3RNkdrO3jO4-e6oVOmpe0nDobUo2joB0w

###

POST  http://localhost:4000/api/conversations?includeNotify=true
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QQHUPaiV4T8W5us0jje_c55BP7LvkFomwX9bXVhQw1jm3joRaWiLKE3Dnd6SkPfotlKZq7wQjKf-d3MHKZymNzlhFG4uTmHjbJYHQmyTYfcdpa0BIc1JmhEEScj3yU9ktoYcndD3-1rbaUNwjin5eB1HhUwVLS7Sj_zUIE7_zz1IO6twtj40ytwwmPp0jvAAk-CVXYoCpsT5yQ7DVLyc5sGRkhns10mqipdFFhCPCQCKac1AFs646czliJAKrCD5RsIwa81zGMfEa3MkC17zRlCLCmTunzdThnvHSOp6gMrIdZ9z1fIsAOyYidbMMWENM1X7TAJSpPl0Z_Cr5lTNSXIyWvhH3FTg6Qz6nZL46JlUgOVcpofMwND-jtnvM6R_ABz1btfz0VgCJosgp3JWI7beltvhoz-9k2ITTs0eN8dAB_gjzOoqDAI5-aVsS5NRtaKsP5cPw5N421XmJNlqpFYcPThNQOsNDpewbwbki93VPP36s1aKdfs7d2x_pr61tUQTxcNaeb2D2A_JQVZuhZxO5XIYzi9jR15iDpa9Kd0g
Content-Type: application/json

{
    "participants": [{
            "contactId": "4817b568-756a-4f92-82fa-be40d82f5274",
            "isNotifying": true,
            "isModerator": true
        }, {
            "contactId": "b8ab2c7e-054c-4711-b062-7443488855e9",
            "isNotifying": true,
            "isDeleted": true
        }
    ]
}

###

PATCH   http://localhost:4000/api/notifications/31786e48-2cac-11ef-b352-0242ac110002
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TjRVXY0uDHiE2dxr6lV-RNvId_oNPpi_UKZ9tc3bgUUCG4sScPYnGStXF9WepUBtKaZSAIejozpwYCTVNBnwIMwBZE65pt921f7xMQmyfhJyNzS04Fr1mQZry4nN3gJNWqceB1rCj4jg6JJz7jfJVVMmgZD0Du0jiZRMH8qWfDbiLigZ3IvAYUdLQOZa1nPqNpxhik9S8N-UDBLJ6M7E2GB8hR_vh4C0taYbErd97kGQxSb9cJE72oQNmyhX3xDdw2oDgEfLe-1MrPH-4mQ1gdsCWJB2GKgH2qPfkUsSATf8UwM2GL-sZw32zYBYt_yC2rKMPTp7M6YLKEKtXK7UBkUyM4HxoANaxODn-WHWPe73lGAiZUHv95LxLPGkzSfFogqAXjF54KZ9s6g2JBKOBKMcMKQBPPmBGY7uRA69CW5dZc5fXN9Di6W95QnTIXmyKk21mGQRgZio3I845kjCgDozz0yJGF-uoxcPtip6bHQld95RN4U3k2nM_Act586IPWm_WGef8ZAL-A1guaF-uy2tg9VIDmBS3XJXQX_u6FKA
Content-Type: application/json

[{"op":"replace","path":"read","value":true}]

###

POST  http://localhost:4000/api/conversations
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9TVzEaG7HASiRHtmvK8y17XDypySsgqRf4r1Ed4cfQ-vKGzCAdKtdu722JKpk6f4XYmQJXqfPVyJRG4X6yEVSPMDJfoywlu6BBER3B58LkKWrjczb2IKCTU0Pkq94HfeL0-WKRzE1S6o7hzv8fw4Bf_pyBcdKcvsWeWGGnN01NF8eCHpBjY-VSbCi_W_v5Cxh_Yn8MaxQ-O_oKanXnLIQwgajYOJy8l9wEX-LIIfPYE-9l0GMt4V0zDHii7Exc7NXvqd1PGr2RzLhjGZeDlMmuXgZcpL5aMixX4hYKFcPkCoSTpmx5QMoSD1BGWGNu09D97zcdRFuUlWVP_ZlOFQiqTGYOWR0tf6ApSnjYiXPNEhCvmx-q3oWoDkCtoLS6budYF5WKM1dPlmVmA-gp6L1JWhajjjmWH7nFtp2g-elamZOA8ThHMWrBDApH6fGKYE0BeSoaxAzKjcqhmerdF1HRPQoHPL06fd809VM-krLrmi5-cogaYjXPGWG8dwfLxFRQ5rBxIvy4QAEUZORHkmgsaXSH4RbeET_Z5XXX8Ib5klw
Content-Type: application/json

{
    "title":"Happy coding",
    "isGroup":true,
    "participants": [{
            "contactId": "6cd0b479-f501-4aed-a033-f390daaff66c",
            "isNotifying": true,
            "isModerator": true
        },{
            "contactId": "80a6d922-c6e9-4332-a519-92dad5b796bc",
            "isNotifying": true
        }
    ]
}

###

POST  http://localhost:4000/api/messages/send
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RPZ-XK6EoldtGegneNX-pRszM7Gi87UZH30qlyXnHa8qp4hQBrpbNFqk64hszYmwNt5cPBDT_0TP4iZvln0CbOGwaTzXr4AU9TjtJ51OVJwip82OaP57f16BB9klCRPDX15Pwdz08t93RqwQY-9oxXFwlOpDHEKhh_96Zgwth0DQDIrP2w1Xo1qI3Ql8jBeHiV8TRw-gF8kfevG_fiioZd6h3kJJphvMcxXIvc31YNM2AAjT5v1rSt2aAam8RHDdX65p9Eyd_OBG77mJxZJdn7GV1si2LQ27pEZs-1vfWXicefChQ3uLXxf4jjFg6BuK86jDAMs7gNF-zAU4TA2pK4U_XRqbVmYQw-yB-VcWqRpRaDJC6WSKN6YJATPrLYF6tnFh5sY6Y0VAeQ22jQK_siJQCbFohxbKQK_VxJkJUuFuJHea0sKsSp1iDJhxqlD965HXIfmoyg12gOkQsfB0uOn5T5EYYdK_hNyxq2rjQfEsOR9ZkVwcc4fcxJupkqznR6suo2ZivI_e0fFAOguiBlEYu4S2UbJTF_deA8itWYWQ
Content-Type: application/json

{
    "type":"text",
    "content":"xin chao 10",
    "contactId":"6cd0b479-f501-4aed-a033-f390daaff66c",
    "conversationId":"9163a82e-d51a-4751-b670-a06c71997ae1"
}

###
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=AIzaSyB7JnGdGGjcoFN3gR8XPVu4nYpVSORuVnA
Content-Type: application/json

{
    "token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJ0cmludCIsImlzcyI6ImZpcmViYXNlLWFkbWluc2RrLWFicWhmQG15Y29ubmVjdC1mMmFmOC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6ImZpcmViYXNlLWFkbWluc2RrLWFicWhmQG15Y29ubmVjdC1mMmFmOC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImF1ZCI6Imh0dHBzOi8vaWRlbnRpdHl0b29sa2l0Lmdvb2dsZWFwaXMuY29tL2dvb2dsZS5pZGVudGl0eS5pZGVudGl0eXRvb2xraXQudjEuSWRlbnRpdHlUb29sa2l0IiwiZXhwIjoxNzE5NTA1ODMxLCJpYXQiOjE3MTk1MDIyMzF9.opYAp9amkOtUGZ2lH5V6w3GyWlDHHY-61eG4tl_TuqmSqsKj_0htjj0epcHxj9uEu7eLOzxr9AdaEv8ti_kXrX-Oxt6HzMsB5NDXTs-nRZJTT618ROuO04A7fLD-gA3z8kjZRm62bWzmJmSkZOjnaHtxTlE_o6JbQaCJ-9ixSbEpJKdlqXlgMQdtMsHO9-LhN9Tva-8hjI3a9RmUJV5l_aiPIq7H_2w9IxemlnSnCxNcmvtX91u5q6qNuAax9ffbQiZh_0a_YTTV8nx6lDPGb_QWpu72PldRZ74fWZHXQy1Zgk5WcdTAdCwj6KScw9tDdfsQCMUmgvNPtoFJtw5K8g",
    "returnSecureToken":true,
    "scope":"https://www.googleapis.com/auth/firebase.messaging"
}

###
POST https://fcm.googleapis.com/v1/projects/myconnect-f2af8/messages:send
Authorization: Bearer ya29.a0AXooCgvI7dnBNlLV3TSEGAbK-8a2AgL7rhs7QXrpEzUzrvuexYbPrXo7EK3UGDCwwkqfFh0-mhtJQIE_zRWccwTbem47-Z8jLuD4n-yOICW0fKVaLbL3g8Z60dhzMvVYGvxBHohLrIODS-Zm9cTCXsZ4Fv77Dy5kwDGUaCgYKAdASARESFQHGX2MieiLWRqCClQX-de6UPm0nSQ0171

###

POST  http://localhost:4000/api/conversations/9163a82e-d51a-4751-b670-a06c71997ae1/participants
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RoW4KFAsWbTnEqEPuhra8ikdGHWhw7QdaUAkxOneyvQfKwmEcujAYP7QRUaVX9gVXUuh2peFKKqTSaUvJ7-4XEDhJQ-ORT_zB59tiXMRMHNEaqhL04Q-29SEJCqdstLhMghPTU6GqX6MZDBisFcUU-PKb45VEen_ZxTCLORNQvgR2DokONyRQQtJawvdOF2re0HzxcDKw9qHWZSIa6TJzJqvxY435ea6gh5WgZ8SRbxiZAq9xUI39eo-yHjNUoBs9Y0XvDh1IoXizJyM7wRHJSfL9L5LituSgi-prZ0WLCEuRym0PrtNRpFlCug57zp4p9gNmkZVx0Y_DLpXXh2Rj-2oyI2apzzImSMFeUkAGCgZIwQ0IeE6pv0XdkQIXlgWYGqqju12y5V5cYQMV0qCf9tzf8KbzGImf9WdDPiTkNt3TBR7kMOUex-ePLqfYyUatP5kxExSB10qoLI8NnGWs1Dyc2rJzgeyr4NFuZSRXFbY8H6m828M5PO0EJpEkgORyrPnDMUyWjZqL-Tr0I-u4l52tCK7Fyf_CrBimSmwqvoA
Content-Type: application/json

[
    {
        "isNotifying":true,
        "contactId":"80a6d922-c6e9-4332-a519-92dad5b796bc",
        "conversationId":"9163a82e-d51a-4751-b670-a06c71997ae1"
    }
]

###
GET  http://localhost:4000/api/contacts?name=tri
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S98GiWzkqj6yECD_eAIb7Hnn9esRzApLv6D1frCPwVnVE5okN-zjeDh-_nm33c1vv1b_wewZ393gzdV6vpENEdLu9UmZLb0tekjYJYZd1wAecOvCyzrzipgu_xD5L9fjcKz6WBrxeQaIU1RRLRyLkNt0LhhRNvfUg7KKg3J-_8W_bOsXNnU0LVGcpHw45x9ri1RuIcJtqFFQ44mDmg9wuvplKNjhtYGpWAuAV37Kp97828V9bPJa_5t5Iwtco3PDaen2Vs0S6WWOhGf5iC20-dSEdu7sSGc7U2NiQXERPmCEDdVNPaSIZ97EY2Ixtcmal9P3eQzvBIpgVk47meU-ZyBkfI7cLJYvjPqoFo26linZZ2mtB5RaIEVhHTmpKz614LQ1zzadwx5tkb7Eps5Gq_dEgcdNFhNy38hSEtzwJWYmBmIjg_y7ZH0GXo2LhM164Oh3Sp1NR8tS3RyYdv4z3dP8fhv58sHf-VXwBwi6WTNt-uD5AB7ZeabnmkSigKN4GZQhkri0ryUnRM95RA-wxUHbYumbbaJ1P83IJm-sj0xA


###
GET  http://localhost:4000/api/contacts?name=tri
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9S98GiWzkqj6yECD_eAIb7Hnn9esRzApLv6D1frCPwVnVE5okN-zjeDh-_nm33c1vv1b_wewZ393gzdV6vpENEdLu9UmZLb0tekjYJYZd1wAecOvCyzrzipgu_xD5L9fjcKz6WBrxeQaIU1RRLRyLkNt0LhhRNvfUg7KKg3J-_8W_bOsXNnU0LVGcpHw45x9ri1RuIcJtqFFQ44mDmg9wuvplKNjhtYGpWAuAV37Kp97828V9bPJa_5t5Iwtco3PDaen2Vs0S6WWOhGf5iC20-dSEdu7sSGc7U2NiQXERPmCEDdVNPaSIZ97EY2Ixtcmal9P3eQzvBIpgVk47meU-ZyBkfI7cLJYvjPqoFo26linZZ2mtB5RaIEVhHTmpKz614LQ1zzadwx5tkb7Eps5Gq_dEgcdNFhNy38hSEtzwJWYmBmIjg_y7ZH0GXo2LhM164Oh3Sp1NR8tS3RyYdv4z3dP8fhv58sHf-VXwBwi6WTNt-uD5AB7ZeabnmkSigKN4GZQhkri0ryUnRM95RA-wxUHbYumbbaJ1P83IJm-sj0xA