POST  http://localhost:4100/api/users/signup
Content-Type: application/json

{
    "Name": "Tri Nguyen",
    "Username": "trint10",
    "Password": "Qwerty@123"
}

###
POST  http://localhost:4100/api/users/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}

###
GET  http://localhost:4100/api/users/token
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9RjMKgYZQiVqNeFOspXgm8OyowBZ_NajdYJYn7odVCsHoZViEbwz5A-eCCOCVUCVT0QZq6FUSNSnXv-sFmzIk-ksU6o--xKQhYVXKily6Hq_sWck0RZayD8iM0vnyaTRDHgebxUwvfmmK2_PYeT1jBqAZyx5ZACOvQV8b50nTJRZx90NeLM1JYgp1Q97g8dLvYf3z8_gHt7AYfC7dkUgYKgF3m__KRvqI1UYfx5ESnLPxZZXOhOfNks0W6IK6YZ8XmzZan_3xeJLSVnJs5X8xhpwrL8OQnDBy9CK7teDNsbfRblIOXsZIDee_As-cM0PViWS0iZKbGOaknF1TR8ymzJxbsiCr0pgeOKGw4cNo1q5PRzgmtteCurseby8JDTGTrD1Eu6RoL90w7g3A4dMbweYrj5RzHYMrZRrMvUfwxohIlafW3pLDC72218QgPfo5Qt6mxkDuQ2bLrw5VfSBIi90l5DjdwSlhj2qF66GHo_Ui5WSS2hTxgbZv3DDNHnhdyXEGHAWNVNbIYkw-M65qmL3mwCcjH-HC9KXHxtI_izLg

###
GET  http://localhost:4000/api/contacts/info
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9SQwQH_HJzPiRmk2MHIw2gsuDdDW3bvLd0zR_Ju0S6y1IZRshTrvUJ5O3rnTSDWXYRV0rUkTnU-_q7WuzK_01P8L7cxdMLXOnaFQmYrpFwAD82HuSPI5rb5yycN93S9sEh6OdwXSGVssPYCzqWOHwBKvyIANxyc5CndBCBTSjsuBh4r7qMjn2XsWTPsGUGmYEhAY93t_jxj-XreKhcccbze_egjM0i3K5BVAZXD9dTtoimtPI7blJnZV_CJuz1h2hc-4iotbP1y-fIcTosgCg3d_lti_0bMtl0sDk7agGYRKNLdY2hfZjxAf6_AmRKA4aviYVZzUAqg3bCds15tROSvSKxTYfJssHgmEW-tbEP99NbMxRzCXUKj25sawQRZowObM78l7RIN8T62DDgYwlIpT8lgJ7epIuBGGaaCopQARoCbEaMLCUwHELNZqVcbvZN3SQ4xFbIonHesJV837MTEHUclPZy-U_VDb2fay15VtU2MXtiIT0sZrNh9h03i7yDjIpWdMrTSZRI1KOOPSFQ1

###
POST  http://localhost:4100/api/users/refresh
Content-Type: application/json

{
    "refreshToken":"CfDJ8CPzuFnSsq5PudvkkW85E9SblOfeujQS1s_AIQdsV7rLKQffXGuP227oShdjDlEkDdkEmnE2z_RQ-c7-C-8ZCCpeB3IkiUd9ZBf5T6PmsVQLNRMmVc5fV3ZbXc1WNIfACgAy3nMINSJyD5DLKo-mqiCuLguZ2zLLiNRWLetMV-3B-83m2CQKmAUv5DbOsjN9J7rxqRJPCU39dS8RkRuSSSUWsjM5W99-FT0TBlLYaYZrq4FPIA_wZiIgp1qHxvVYW_OKca0ZEC969hV0hHL3KwhwSHR4jGUo-FHpP4OO2D4srq0PMVGIH80P2V0fAiGiPj1JqE01advlOxhLPSwhxWVXHVsNYmpM5j8Sqd5EMwgQG2Hb_MFHAydAeYU4Gl-WRua8ct2EgoCrZSyDO5ljcoh6PkL-adXPIOsO0ExiCNBDdzaUPy8kibBy3U2bZddrfkUFGItA0-b7BTLJhLuww17hPud8p1vYY3gPRapOKjSR2BahGwks3lpuWn2D2hnVKvGOKzGAYqOwfAc1HV3NiM-ucTKk0plz20fsHDQr2cULXV_nwk3KUvFsxKxoAbWu9g"    
}

###

GET  http://localhost:4000/api/conversations
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9T1Fdmv8qwNvvAxIPdPIoJYICcT4ayBaavC-IDyoYlfXYBIB2-xQiXjDf4TWpFE61k_8ikRBxHpp_ii9utdShGnU2x10zBdiGDHu06Ungl3n9PEF2QClKL64Q8icXlz709Bf9w-pDrTRYlu3qRsWe5MmWQ-C48wy8VaxGVh2fhlbRSUuHvOtfCz3gouCreCKaHBs47ca2X6wk2L7OlHMRLQkMXYJVaBF8AwNeN5PSvDHr1OfM9TC-kI8xrC0tsgGilNfaUhFefd2wYAuEeYWa4-aWfDuauuVznJADrb0GlytMCLo5C7md35o57DP-lymdZG0FP7TmzxQdtpucSvazDoYdUvbxcp2Dyt4XkBsBiIy7sPucWkZNTClsEuukCwhruUDzx_0VbpCxz-QIDLtLDXUMPH7LXpEi-wg3LsamFA_fDIgvFgTDI-sr2j27DRc0gkrcd_YbSVq6_zKi352Gi84FozovbRJn33o9rhXA1B31i1OiZAAjx51XLsAYitAOju9S6LW5jyk3RNkdrO3jO4-e6oVOmpe0nDobUo2joB0w

###

POST  http://localhost:4000/api/conversations?includeNotify=true
Authorization: Bearer CfDJ8CPzuFnSsq5PudvkkW85E9QQHUPaiV4T8W5us0jje_c55BP7LvkFomwX9bXVhQw1jm3joRaWiLKE3Dnd6SkPfotlKZq7wQjKf-d3MHKZymNzlhFG4uTmHjbJYHQmyTYfcdpa0BIc1JmhEEScj3yU9ktoYcndD3-1rbaUNwjin5eB1HhUwVLS7Sj_zUIE7_zz1IO6twtj40ytwwmPp0jvAAk-CVXYoCpsT5yQ7DVLyc5sGRkhns10mqipdFFhCPCQCKac1AFs646czliJAKrCD5RsIwa81zGMfEa3MkC17zRlCLCmTunzdThnvHSOp6gMrIdZ9z1fIsAOyYidbMMWENM1X7TAJSpPl0Z_Cr5lTNSXIyWvhH3FTg6Qz6nZL46JlUgOVcpofMwND-jtnvM6R_ABz1btfz0VgCJosgp3JWI7beltvhoz-9k2ITTs0eN8dAB_gjzOoqDAI5-aVsS5NRtaKsP5cPw5N421XmJNlqpFYcPThNQOsNDpewbwbki93VPP36s1aKdfs7d2x_pr61tUQTxcNaeb2D2A_JQVZuhZxO5XIYzi9jR15iDpa9Kd0g
Content-Type: application/json

{
    "participants": [{
            "contactId": "4817b568-756a-4f92-82fa-be40d82f5274",
            "isNotifying": true,
            "isModerator": true
        }, {
            "contactId": "b8ab2c7e-054c-4711-b062-7443488855e9",
            "isNotifying": true,
            "isDeleted": true
        }
    ]
}