global using Domain.Constants;
global using Infrastructure.Repository;
global using Infrastructure.UOW;
global using Notification.API;
global using System.Text.Json;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.JsonPatch;
global using Infrastructure.BaseService;
global using AutoMapper;
global using Domain.Utils;
global using Model = Infrastructure.Repository;