global using System.Linq.Expressions;
global using Microsoft.EntityFrameworkCore;
global using Domain.Features;
global using Infrastructure.Databases;
global using Microsoft.AspNetCore.Authorization;
global using System.Text.Json;
global using System.Text;
global using StackExchange.Redis;
global using Newtonsoft.Json;
global using Infrastructure.Constants;
global using System.Net.Http.Headers;
global using Infrastructure.Middleware;
global using Microsoft.EntityFrameworkCore.Storage;
global using System.Data;
global using Infrastructure.Middleware.Exceptions;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Diagnostics;
global using FirebaseAdmin;
global using Google.Apis.Auth.OAuth2;
global using FirebaseAdmin.Messaging;
global using Message = Domain.Features.Message;
global using Notification = Domain.Features.Notification;