@host = http://localhost:4000/api
# @host = https://chat.happycoding.click/chat/api

###
POST {{host}}/identity/signin
Content-Type: application/json

{
    "Username":"trint",
    "Password":"Qwerty@123"
}
 
###
GET  {{host}}/friends
 
###
GET  {{host}}/friends/66f3af1f9c335e65456dc1f1

### Send friend request
POST  {{host}}/contacts/66fbbf0b81582e1dcda3a4cc/friends

### Accept friend request
PUT   {{host}}/friends/66f2830dc469ba88ce1924cc

### Cancel friend request
DELETE   {{host}}/friends/6715ed930a40c8b32a813f10